// Package main generates the embedded bundled OpenAPI asset consumed by server/internal/app.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
)

const (
	sourceRepoPath = "openapi/dist/openapi.bundle.json"
	outputFileName = "zz_openapi_bundle_generated.go"
	outputFileMode = 0o600
)

// main 读取 OpenAPI 打包文件，计算其 SHA-256 摘要，并生成包含内置 JSON 和摘要常量的 Go 源代码文件。
func main() {
	workdir, err := os.Getwd()
	if err != nil {
		failf("resolve working directory: %v", err)
	}

	serverRoot := filepath.Clean(filepath.Join(workdir, "..", ".."))
	repositoryRoot := filepath.Clean(filepath.Join(serverRoot, ".."))
	sourcePath := filepath.Join(repositoryRoot, filepath.FromSlash(sourceRepoPath))

	sourceInfo, err := os.Lstat(sourcePath)
	if err != nil {
		failf("stat canonical bundled openapi spec: %v", err)
	}
	if sourceInfo.Mode()&os.ModeSymlink != 0 {
		failf("reject symlink canonical bundled openapi spec: %s", sourcePath)
	}
	if !sourceInfo.Mode().IsRegular() {
		failf("reject non-regular canonical bundled openapi spec: %s (%s)", sourcePath, sourceInfo.Mode().String())
	}

	// sourcePath is deterministically derived from the repository layout above and prevalidated as a regular file.
	spec, err := os.ReadFile(sourcePath) // #nosec G304
	if err != nil {
		failf("read canonical bundled openapi spec: %v", err)
	}

	digest := sha256.Sum256(spec)
	content := renderGeneratedSource(spec, hex.EncodeToString(digest[:]))
	outputPath := filepath.Join(workdir, outputFileName)
	if err := os.WriteFile(outputPath, content, outputFileMode); err != nil {
		failf("write generated docs asset: %v", err)
	}
}

// renderGeneratedSource 生成嵌入 OpenAPI 打包产物和其 SHA-256 摘要的 Go 源代码。
func renderGeneratedSource(spec []byte, digest string) []byte {
	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	buffer.WriteString("package app\n\n")
	buffer.WriteString("// generatedOpenAPIBundleSHA256 lets validate freshness compare the runtime asset with the canonical bundle.\n")
	_, _ = fmt.Fprintf(&buffer, "const generatedOpenAPIBundleSHA256 = %q\n\n", digest)
	_, _ = fmt.Fprintf(&buffer, "var generatedOpenAPIBundleJSON = []byte(%q)\n", string(spec))
	return buffer.Bytes()
}

// failf formats and writes a message to standard error and terminates the program with exit status 1.
func failf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
