// Package monitor provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package monitor

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetMonitorServerStatusParamsTrendRange.
const (
	GetMonitorServerStatusParamsTrendRangeN10m GetMonitorServerStatusParamsTrendRange = "10m"
	GetMonitorServerStatusParamsTrendRangeN1h  GetMonitorServerStatusParamsTrendRange = "1h"
	GetMonitorServerStatusParamsTrendRangeN30m GetMonitorServerStatusParamsTrendRange = "30m"
)

// Valid indicates whether the value is a known member of the GetMonitorServerStatusParamsTrendRange enum.
func (e GetMonitorServerStatusParamsTrendRange) Valid() bool {
	switch e {
	case GetMonitorServerStatusParamsTrendRangeN10m:
		return true
	case GetMonitorServerStatusParamsTrendRangeN1h:
		return true
	case GetMonitorServerStatusParamsTrendRangeN30m:
		return true
	default:
		return false
	}
}

// Defines values for GetMonitorServerStatus200JSONResponseBodyDataTrendRange.
const (
	GetMonitorServerStatus200JSONResponseBodyDataTrendRangeN10m GetMonitorServerStatus200JSONResponseBodyDataTrendRange = "10m"
	GetMonitorServerStatus200JSONResponseBodyDataTrendRangeN1h  GetMonitorServerStatus200JSONResponseBodyDataTrendRange = "1h"
	GetMonitorServerStatus200JSONResponseBodyDataTrendRangeN30m GetMonitorServerStatus200JSONResponseBodyDataTrendRange = "30m"
)

// Valid indicates whether the value is a known member of the GetMonitorServerStatus200JSONResponseBodyDataTrendRange enum.
func (e GetMonitorServerStatus200JSONResponseBodyDataTrendRange) Valid() bool {
	switch e {
	case GetMonitorServerStatus200JSONResponseBodyDataTrendRangeN10m:
		return true
	case GetMonitorServerStatus200JSONResponseBodyDataTrendRangeN1h:
		return true
	case GetMonitorServerStatus200JSONResponseBodyDataTrendRangeN30m:
		return true
	default:
		return false
	}
}

// Defines values for GetMonitorServerStatus401JSONResponseBodySuccess.
const (
	GetMonitorServerStatus401JSONResponseBodySuccessFalse GetMonitorServerStatus401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetMonitorServerStatus401JSONResponseBodySuccess enum.
func (e GetMonitorServerStatus401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetMonitorServerStatus401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetMonitorServerStatus403JSONResponseBodySuccess.
const (
	GetMonitorServerStatus403JSONResponseBodySuccessFalse GetMonitorServerStatus403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetMonitorServerStatus403JSONResponseBodySuccess enum.
func (e GetMonitorServerStatus403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetMonitorServerStatus403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetMonitorServerStatus500JSONResponseBodySuccess.
const (
	False GetMonitorServerStatus500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetMonitorServerStatus500JSONResponseBodySuccess enum.
func (e GetMonitorServerStatus500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// GetMonitorServerStatusParams defines parameters for GetMonitorServerStatus.
type GetMonitorServerStatusParams struct {
	// TrendRange Optional trend window. Invalid values currently fall back to the backend default `10m`.
	TrendRange *GetMonitorServerStatusParamsTrendRange `form:"trend_range,omitempty" json:"trend_range,omitempty"`

	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetMonitorServerStatusParamsTrendRange defines parameters for GetMonitorServerStatus.
type GetMonitorServerStatusParamsTrendRange string

// GetMonitorServerStatus200JSONResponseBodyDataTrendRange defines parameters for GetMonitorServerStatus.
type GetMonitorServerStatus200JSONResponseBodyDataTrendRange string

// GetMonitorServerStatus401JSONResponseBodySuccess defines parameters for GetMonitorServerStatus.
type GetMonitorServerStatus401JSONResponseBodySuccess bool

// GetMonitorServerStatus403JSONResponseBodySuccess defines parameters for GetMonitorServerStatus.
type GetMonitorServerStatus403JSONResponseBodySuccess bool

// GetMonitorServerStatus500JSONResponseBodySuccess defines parameters for GetMonitorServerStatus.
type GetMonitorServerStatus500JSONResponseBodySuccess bool
