// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true, Comment: "权限点编码，采用点分层级格式"},
		{Name: "display", Type: field.TypeString, Comment: "权限点显示名称"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "权限点描述"},
		{Name: "category", Type: field.TypeString, Comment: "权限类别：api 表示接口权限", Default: "api"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "created_by", Type: field.TypeUint64, Comment: "创建人用户 ID，0 表示系统", Default: 0},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "updated_by", Type: field.TypeUint64, Comment: "最后更新人用户 ID，0 表示系统", Default: 0},
		{Name: "deleted_at", Type: field.TypeInt64, Comment: "软删除时间戳，0 表示未删除", Default: 0},
		{Name: "deleted_by", Type: field.TypeUint64, Comment: "删除人用户 ID，0 表示未删除", Default: 0},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Comment:    "权限点信息表（RBAC 插件）",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Comment: "角色标识名称，用于唯一识别角色"},
		{Name: "display", Type: field.TypeString, Comment: "角色显示名称"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "角色描述"},
		{Name: "builtin", Type: field.TypeBool, Comment: "是否为系统内置角色", Default: false},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "created_by", Type: field.TypeUint64, Comment: "创建人用户 ID，0 表示系统", Default: 0},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "updated_by", Type: field.TypeUint64, Comment: "最后更新人用户 ID，0 表示系统", Default: 0},
		{Name: "deleted_at", Type: field.TypeInt64, Comment: "软删除时间戳，0 表示未删除", Default: 0},
		{Name: "deleted_by", Type: field.TypeUint64, Comment: "删除人用户 ID，0 表示未删除", Default: 0},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Comment:    "角色信息表（RBAC 插件）",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "permission_id", Type: field.TypeInt, Comment: "权限 ID"},
		{Name: "role_id", Type: field.TypeInt, Comment: "角色 ID"},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Comment:    "角色与权限关联表（RBAC 插件）",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_permissions_role_permissions",
				Columns:    []*schema.Column{RolePermissionsColumns[2]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "role_permissions_roles_role_permissions",
				Columns:    []*schema.Column{RolePermissionsColumns[3]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rolepermission_role_id_permission_id",
				Unique:  true,
				Columns: []*schema.Column{RolePermissionsColumns[3], RolePermissionsColumns[2]},
			},
			{
				Name:    "rolepermission_permission_id",
				Unique:  false,
				Columns: []*schema.Column{RolePermissionsColumns[2]},
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt, Comment: "用户 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "role_id", Type: field.TypeInt, Comment: "角色 ID"},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Comment:    "用户与角色关联表（RBAC 插件）",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_roles_user_roles",
				Columns:    []*schema.Column{UserRolesColumns[3]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userrole_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{UserRolesColumns[1], UserRolesColumns[3]},
			},
			{
				Name:    "userrole_role_id",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PermissionsTable,
		RolesTable,
		RolePermissionsTable,
		UserRolesTable,
	}
)

func init() {
	PermissionsTable.Annotation = &entsql.Annotation{
		Table: "permissions",
	}
	RolesTable.Annotation = &entsql.Annotation{
		Table: "roles",
	}
	RolePermissionsTable.ForeignKeys[0].RefTable = PermissionsTable
	RolePermissionsTable.ForeignKeys[1].RefTable = RolesTable
	RolePermissionsTable.Annotation = &entsql.Annotation{
		Table: "role_permissions",
	}
	UserRolesTable.ForeignKeys[0].RefTable = RolesTable
	UserRolesTable.Annotation = &entsql.Annotation{
		Table: "user_roles",
	}
}
