CREATE TABLE IF NOT EXISTS "users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "username" character varying NOT NULL,
  "display" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'enabled',
  "password_hash" character varying NULL,
  "must_change_password" boolean NOT NULL DEFAULT false,
  "password_changed_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "created_by" bigint NOT NULL DEFAULT 0,
  "updated_at" timestamptz NOT NULL,
  "updated_by" bigint NOT NULL DEFAULT 0,
  "deleted_at" bigint NOT NULL DEFAULT 0,
  "deleted_by" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "users_username_key" ON "users" ("username");
CREATE INDEX IF NOT EXISTS "users_deleted_at_idx" ON "users" ("deleted_at");

CREATE TABLE IF NOT EXISTS "refresh_sessions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "token_id" character varying NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz NULL,
  "replaced_by_token_id" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "refresh_sessions_users_refresh_sessions"
    FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE UNIQUE INDEX IF NOT EXISTS "refresh_sessions_token_id_key" ON "refresh_sessions" ("token_id");
CREATE INDEX IF NOT EXISTS "refreshsession_user_id" ON "refresh_sessions" ("user_id");
CREATE INDEX IF NOT EXISTS "refreshsession_expires_at" ON "refresh_sessions" ("expires_at");

COMMENT ON TABLE "users" IS '用户基础信息表（用户模块）';
COMMENT ON COLUMN "users"."id" IS '主键 ID';
COMMENT ON COLUMN "users"."username" IS '用户名，用于登录和唯一标识';
COMMENT ON COLUMN "users"."display" IS '显示名称，用于后台展示';
COMMENT ON COLUMN "users"."status" IS '状态：enabled 启用，disabled 禁用';
COMMENT ON COLUMN "users"."password_hash" IS '密码哈希值';
COMMENT ON COLUMN "users"."must_change_password" IS '是否必须在下次登录后修改密码';
COMMENT ON COLUMN "users"."password_changed_at" IS '最近一次修改密码时间';
COMMENT ON COLUMN "users"."created_at" IS '创建时间';
COMMENT ON COLUMN "users"."created_by" IS '创建人用户 ID，0 表示系统';
COMMENT ON COLUMN "users"."updated_at" IS '更新时间';
COMMENT ON COLUMN "users"."updated_by" IS '最后更新人用户 ID，0 表示系统';
COMMENT ON COLUMN "users"."deleted_at" IS '软删除时间戳，0 表示未删除';
COMMENT ON COLUMN "users"."deleted_by" IS '删除人用户 ID，0 表示未删除';

COMMENT ON TABLE "refresh_sessions" IS '刷新令牌会话表（用户模块）';
COMMENT ON COLUMN "refresh_sessions"."id" IS '主键 ID';
COMMENT ON COLUMN "refresh_sessions"."token_id" IS '刷新令牌唯一标识';
COMMENT ON COLUMN "refresh_sessions"."expires_at" IS '过期时间';
COMMENT ON COLUMN "refresh_sessions"."revoked_at" IS '撤销时间，为空表示未撤销';
COMMENT ON COLUMN "refresh_sessions"."replaced_by_token_id" IS '轮换后替换当前令牌的新令牌 ID';
COMMENT ON COLUMN "refresh_sessions"."created_at" IS '创建时间';
COMMENT ON COLUMN "refresh_sessions"."updated_at" IS '更新时间';
COMMENT ON COLUMN "refresh_sessions"."user_id" IS '所属用户 ID';
