// Package containeropenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package containeropenapi

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetContainers200JSONResponseBodyDataItemsPortsType.
const (
	GetContainers200JSONResponseBodyDataItemsPortsTypeSctp GetContainers200JSONResponseBodyDataItemsPortsType = "sctp"
	GetContainers200JSONResponseBodyDataItemsPortsTypeTcp  GetContainers200JSONResponseBodyDataItemsPortsType = "tcp"
	GetContainers200JSONResponseBodyDataItemsPortsTypeUdp  GetContainers200JSONResponseBodyDataItemsPortsType = "udp"
)

// Valid indicates whether the value is a known member of the GetContainers200JSONResponseBodyDataItemsPortsType enum.
func (e GetContainers200JSONResponseBodyDataItemsPortsType) Valid() bool {
	switch e {
	case GetContainers200JSONResponseBodyDataItemsPortsTypeSctp:
		return true
	case GetContainers200JSONResponseBodyDataItemsPortsTypeTcp:
		return true
	case GetContainers200JSONResponseBodyDataItemsPortsTypeUdp:
		return true
	default:
		return false
	}
}

// Defines values for GetContainers200JSONResponseBodyDataItemsState.
const (
	GetContainers200JSONResponseBodyDataItemsStateCreated    GetContainers200JSONResponseBodyDataItemsState = "created"
	GetContainers200JSONResponseBodyDataItemsStateDead       GetContainers200JSONResponseBodyDataItemsState = "dead"
	GetContainers200JSONResponseBodyDataItemsStateExited     GetContainers200JSONResponseBodyDataItemsState = "exited"
	GetContainers200JSONResponseBodyDataItemsStatePaused     GetContainers200JSONResponseBodyDataItemsState = "paused"
	GetContainers200JSONResponseBodyDataItemsStateRemoving   GetContainers200JSONResponseBodyDataItemsState = "removing"
	GetContainers200JSONResponseBodyDataItemsStateRestarting GetContainers200JSONResponseBodyDataItemsState = "restarting"
	GetContainers200JSONResponseBodyDataItemsStateRunning    GetContainers200JSONResponseBodyDataItemsState = "running"
	GetContainers200JSONResponseBodyDataItemsStateUnknown    GetContainers200JSONResponseBodyDataItemsState = "unknown"
)

// Valid indicates whether the value is a known member of the GetContainers200JSONResponseBodyDataItemsState enum.
func (e GetContainers200JSONResponseBodyDataItemsState) Valid() bool {
	switch e {
	case GetContainers200JSONResponseBodyDataItemsStateCreated:
		return true
	case GetContainers200JSONResponseBodyDataItemsStateDead:
		return true
	case GetContainers200JSONResponseBodyDataItemsStateExited:
		return true
	case GetContainers200JSONResponseBodyDataItemsStatePaused:
		return true
	case GetContainers200JSONResponseBodyDataItemsStateRemoving:
		return true
	case GetContainers200JSONResponseBodyDataItemsStateRestarting:
		return true
	case GetContainers200JSONResponseBodyDataItemsStateRunning:
		return true
	case GetContainers200JSONResponseBodyDataItemsStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for GetContainers200JSONResponseBodyDataRuntimeStatus.
const (
	GetContainers200JSONResponseBodyDataRuntimeStatusDisabled    GetContainers200JSONResponseBodyDataRuntimeStatus = "disabled"
	GetContainers200JSONResponseBodyDataRuntimeStatusEnabled     GetContainers200JSONResponseBodyDataRuntimeStatus = "enabled"
	GetContainers200JSONResponseBodyDataRuntimeStatusUnavailable GetContainers200JSONResponseBodyDataRuntimeStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the GetContainers200JSONResponseBodyDataRuntimeStatus enum.
func (e GetContainers200JSONResponseBodyDataRuntimeStatus) Valid() bool {
	switch e {
	case GetContainers200JSONResponseBodyDataRuntimeStatusDisabled:
		return true
	case GetContainers200JSONResponseBodyDataRuntimeStatusEnabled:
		return true
	case GetContainers200JSONResponseBodyDataRuntimeStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for GetContainers401JSONResponseBodySuccess.
const (
	GetContainers401JSONResponseBodySuccessFalse GetContainers401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainers401JSONResponseBodySuccess enum.
func (e GetContainers401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainers401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainers403JSONResponseBodySuccess.
const (
	GetContainers403JSONResponseBodySuccessFalse GetContainers403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainers403JSONResponseBodySuccess enum.
func (e GetContainers403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainers403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainers500JSONResponseBodySuccess.
const (
	GetContainers500JSONResponseBodySuccessFalse GetContainers500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainers500JSONResponseBodySuccess enum.
func (e GetContainers500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainers500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainer200JSONResponseBodyDataPortsType.
const (
	GetContainer200JSONResponseBodyDataPortsTypeSctp GetContainer200JSONResponseBodyDataPortsType = "sctp"
	GetContainer200JSONResponseBodyDataPortsTypeTcp  GetContainer200JSONResponseBodyDataPortsType = "tcp"
	GetContainer200JSONResponseBodyDataPortsTypeUdp  GetContainer200JSONResponseBodyDataPortsType = "udp"
)

// Valid indicates whether the value is a known member of the GetContainer200JSONResponseBodyDataPortsType enum.
func (e GetContainer200JSONResponseBodyDataPortsType) Valid() bool {
	switch e {
	case GetContainer200JSONResponseBodyDataPortsTypeSctp:
		return true
	case GetContainer200JSONResponseBodyDataPortsTypeTcp:
		return true
	case GetContainer200JSONResponseBodyDataPortsTypeUdp:
		return true
	default:
		return false
	}
}

// Defines values for GetContainer200JSONResponseBodyDataRuntimeInfoStatus.
const (
	GetContainer200JSONResponseBodyDataRuntimeInfoStatusDisabled    GetContainer200JSONResponseBodyDataRuntimeInfoStatus = "disabled"
	GetContainer200JSONResponseBodyDataRuntimeInfoStatusEnabled     GetContainer200JSONResponseBodyDataRuntimeInfoStatus = "enabled"
	GetContainer200JSONResponseBodyDataRuntimeInfoStatusUnavailable GetContainer200JSONResponseBodyDataRuntimeInfoStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the GetContainer200JSONResponseBodyDataRuntimeInfoStatus enum.
func (e GetContainer200JSONResponseBodyDataRuntimeInfoStatus) Valid() bool {
	switch e {
	case GetContainer200JSONResponseBodyDataRuntimeInfoStatusDisabled:
		return true
	case GetContainer200JSONResponseBodyDataRuntimeInfoStatusEnabled:
		return true
	case GetContainer200JSONResponseBodyDataRuntimeInfoStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for GetContainer200JSONResponseBodyDataState.
const (
	GetContainer200JSONResponseBodyDataStateCreated    GetContainer200JSONResponseBodyDataState = "created"
	GetContainer200JSONResponseBodyDataStateDead       GetContainer200JSONResponseBodyDataState = "dead"
	GetContainer200JSONResponseBodyDataStateExited     GetContainer200JSONResponseBodyDataState = "exited"
	GetContainer200JSONResponseBodyDataStatePaused     GetContainer200JSONResponseBodyDataState = "paused"
	GetContainer200JSONResponseBodyDataStateRemoving   GetContainer200JSONResponseBodyDataState = "removing"
	GetContainer200JSONResponseBodyDataStateRestarting GetContainer200JSONResponseBodyDataState = "restarting"
	GetContainer200JSONResponseBodyDataStateRunning    GetContainer200JSONResponseBodyDataState = "running"
	GetContainer200JSONResponseBodyDataStateUnknown    GetContainer200JSONResponseBodyDataState = "unknown"
)

// Valid indicates whether the value is a known member of the GetContainer200JSONResponseBodyDataState enum.
func (e GetContainer200JSONResponseBodyDataState) Valid() bool {
	switch e {
	case GetContainer200JSONResponseBodyDataStateCreated:
		return true
	case GetContainer200JSONResponseBodyDataStateDead:
		return true
	case GetContainer200JSONResponseBodyDataStateExited:
		return true
	case GetContainer200JSONResponseBodyDataStatePaused:
		return true
	case GetContainer200JSONResponseBodyDataStateRemoving:
		return true
	case GetContainer200JSONResponseBodyDataStateRestarting:
		return true
	case GetContainer200JSONResponseBodyDataStateRunning:
		return true
	case GetContainer200JSONResponseBodyDataStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for GetContainer400JSONResponseBodySuccess.
const (
	GetContainer400JSONResponseBodySuccessFalse GetContainer400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainer400JSONResponseBodySuccess enum.
func (e GetContainer400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainer400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainer401JSONResponseBodySuccess.
const (
	GetContainer401JSONResponseBodySuccessFalse GetContainer401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainer401JSONResponseBodySuccess enum.
func (e GetContainer401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainer401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainer403JSONResponseBodySuccess.
const (
	GetContainer403JSONResponseBodySuccessFalse GetContainer403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainer403JSONResponseBodySuccess enum.
func (e GetContainer403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainer403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainer404JSONResponseBodySuccess.
const (
	GetContainer404JSONResponseBodySuccessFalse GetContainer404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainer404JSONResponseBodySuccess enum.
func (e GetContainer404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainer404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainer500JSONResponseBodySuccess.
const (
	GetContainer500JSONResponseBodySuccessFalse GetContainer500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainer500JSONResponseBodySuccess enum.
func (e GetContainer500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainer500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainerLogs400JSONResponseBodySuccess.
const (
	GetContainerLogs400JSONResponseBodySuccessFalse GetContainerLogs400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainerLogs400JSONResponseBodySuccess enum.
func (e GetContainerLogs400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainerLogs400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainerLogs401JSONResponseBodySuccess.
const (
	GetContainerLogs401JSONResponseBodySuccessFalse GetContainerLogs401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainerLogs401JSONResponseBodySuccess enum.
func (e GetContainerLogs401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainerLogs401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainerLogs403JSONResponseBodySuccess.
const (
	GetContainerLogs403JSONResponseBodySuccessFalse GetContainerLogs403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainerLogs403JSONResponseBodySuccess enum.
func (e GetContainerLogs403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainerLogs403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainerLogs404JSONResponseBodySuccess.
const (
	GetContainerLogs404JSONResponseBodySuccessFalse GetContainerLogs404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainerLogs404JSONResponseBodySuccess enum.
func (e GetContainerLogs404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainerLogs404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetContainerLogs500JSONResponseBodySuccess.
const (
	GetContainerLogs500JSONResponseBodySuccessFalse GetContainerLogs500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetContainerLogs500JSONResponseBodySuccess enum.
func (e GetContainerLogs500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetContainerLogs500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerRestart200JSONResponseBodyDataAction.
const (
	PostContainerRestart200JSONResponseBodyDataActionRestart PostContainerRestart200JSONResponseBodyDataAction = "restart"
	PostContainerRestart200JSONResponseBodyDataActionStart   PostContainerRestart200JSONResponseBodyDataAction = "start"
	PostContainerRestart200JSONResponseBodyDataActionStop    PostContainerRestart200JSONResponseBodyDataAction = "stop"
)

// Valid indicates whether the value is a known member of the PostContainerRestart200JSONResponseBodyDataAction enum.
func (e PostContainerRestart200JSONResponseBodyDataAction) Valid() bool {
	switch e {
	case PostContainerRestart200JSONResponseBodyDataActionRestart:
		return true
	case PostContainerRestart200JSONResponseBodyDataActionStart:
		return true
	case PostContainerRestart200JSONResponseBodyDataActionStop:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerRestart200JSONResponseBodyDataResult.
const (
	PostContainerRestart200JSONResponseBodyDataResultAccepted  PostContainerRestart200JSONResponseBodyDataResult = "accepted"
	PostContainerRestart200JSONResponseBodyDataResultCompleted PostContainerRestart200JSONResponseBodyDataResult = "completed"
	PostContainerRestart200JSONResponseBodyDataResultUnchanged PostContainerRestart200JSONResponseBodyDataResult = "unchanged"
)

// Valid indicates whether the value is a known member of the PostContainerRestart200JSONResponseBodyDataResult enum.
func (e PostContainerRestart200JSONResponseBodyDataResult) Valid() bool {
	switch e {
	case PostContainerRestart200JSONResponseBodyDataResultAccepted:
		return true
	case PostContainerRestart200JSONResponseBodyDataResultCompleted:
		return true
	case PostContainerRestart200JSONResponseBodyDataResultUnchanged:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerRestart400JSONResponseBodySuccess.
const (
	PostContainerRestart400JSONResponseBodySuccessFalse PostContainerRestart400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerRestart400JSONResponseBodySuccess enum.
func (e PostContainerRestart400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerRestart400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerRestart401JSONResponseBodySuccess.
const (
	PostContainerRestart401JSONResponseBodySuccessFalse PostContainerRestart401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerRestart401JSONResponseBodySuccess enum.
func (e PostContainerRestart401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerRestart401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerRestart403JSONResponseBodySuccess.
const (
	PostContainerRestart403JSONResponseBodySuccessFalse PostContainerRestart403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerRestart403JSONResponseBodySuccess enum.
func (e PostContainerRestart403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerRestart403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerRestart404JSONResponseBodySuccess.
const (
	PostContainerRestart404JSONResponseBodySuccessFalse PostContainerRestart404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerRestart404JSONResponseBodySuccess enum.
func (e PostContainerRestart404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerRestart404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerRestart409JSONResponseBodySuccess.
const (
	PostContainerRestart409JSONResponseBodySuccessFalse PostContainerRestart409JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerRestart409JSONResponseBodySuccess enum.
func (e PostContainerRestart409JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerRestart409JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerRestart500JSONResponseBodySuccess.
const (
	PostContainerRestart500JSONResponseBodySuccessFalse PostContainerRestart500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerRestart500JSONResponseBodySuccess enum.
func (e PostContainerRestart500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerRestart500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStart200JSONResponseBodyDataAction.
const (
	PostContainerStart200JSONResponseBodyDataActionRestart PostContainerStart200JSONResponseBodyDataAction = "restart"
	PostContainerStart200JSONResponseBodyDataActionStart   PostContainerStart200JSONResponseBodyDataAction = "start"
	PostContainerStart200JSONResponseBodyDataActionStop    PostContainerStart200JSONResponseBodyDataAction = "stop"
)

// Valid indicates whether the value is a known member of the PostContainerStart200JSONResponseBodyDataAction enum.
func (e PostContainerStart200JSONResponseBodyDataAction) Valid() bool {
	switch e {
	case PostContainerStart200JSONResponseBodyDataActionRestart:
		return true
	case PostContainerStart200JSONResponseBodyDataActionStart:
		return true
	case PostContainerStart200JSONResponseBodyDataActionStop:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStart200JSONResponseBodyDataResult.
const (
	PostContainerStart200JSONResponseBodyDataResultAccepted  PostContainerStart200JSONResponseBodyDataResult = "accepted"
	PostContainerStart200JSONResponseBodyDataResultCompleted PostContainerStart200JSONResponseBodyDataResult = "completed"
	PostContainerStart200JSONResponseBodyDataResultUnchanged PostContainerStart200JSONResponseBodyDataResult = "unchanged"
)

// Valid indicates whether the value is a known member of the PostContainerStart200JSONResponseBodyDataResult enum.
func (e PostContainerStart200JSONResponseBodyDataResult) Valid() bool {
	switch e {
	case PostContainerStart200JSONResponseBodyDataResultAccepted:
		return true
	case PostContainerStart200JSONResponseBodyDataResultCompleted:
		return true
	case PostContainerStart200JSONResponseBodyDataResultUnchanged:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStart400JSONResponseBodySuccess.
const (
	PostContainerStart400JSONResponseBodySuccessFalse PostContainerStart400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStart400JSONResponseBodySuccess enum.
func (e PostContainerStart400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStart400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStart401JSONResponseBodySuccess.
const (
	PostContainerStart401JSONResponseBodySuccessFalse PostContainerStart401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStart401JSONResponseBodySuccess enum.
func (e PostContainerStart401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStart401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStart403JSONResponseBodySuccess.
const (
	PostContainerStart403JSONResponseBodySuccessFalse PostContainerStart403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStart403JSONResponseBodySuccess enum.
func (e PostContainerStart403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStart403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStart404JSONResponseBodySuccess.
const (
	PostContainerStart404JSONResponseBodySuccessFalse PostContainerStart404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStart404JSONResponseBodySuccess enum.
func (e PostContainerStart404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStart404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStart409JSONResponseBodySuccess.
const (
	PostContainerStart409JSONResponseBodySuccessFalse PostContainerStart409JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStart409JSONResponseBodySuccess enum.
func (e PostContainerStart409JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStart409JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStart500JSONResponseBodySuccess.
const (
	PostContainerStart500JSONResponseBodySuccessFalse PostContainerStart500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStart500JSONResponseBodySuccess enum.
func (e PostContainerStart500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStart500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStop200JSONResponseBodyDataAction.
const (
	Restart PostContainerStop200JSONResponseBodyDataAction = "restart"
	Start   PostContainerStop200JSONResponseBodyDataAction = "start"
	Stop    PostContainerStop200JSONResponseBodyDataAction = "stop"
)

// Valid indicates whether the value is a known member of the PostContainerStop200JSONResponseBodyDataAction enum.
func (e PostContainerStop200JSONResponseBodyDataAction) Valid() bool {
	switch e {
	case Restart:
		return true
	case Start:
		return true
	case Stop:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStop200JSONResponseBodyDataResult.
const (
	Accepted  PostContainerStop200JSONResponseBodyDataResult = "accepted"
	Completed PostContainerStop200JSONResponseBodyDataResult = "completed"
	Unchanged PostContainerStop200JSONResponseBodyDataResult = "unchanged"
)

// Valid indicates whether the value is a known member of the PostContainerStop200JSONResponseBodyDataResult enum.
func (e PostContainerStop200JSONResponseBodyDataResult) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Completed:
		return true
	case Unchanged:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStop400JSONResponseBodySuccess.
const (
	PostContainerStop400JSONResponseBodySuccessFalse PostContainerStop400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStop400JSONResponseBodySuccess enum.
func (e PostContainerStop400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStop400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStop401JSONResponseBodySuccess.
const (
	PostContainerStop401JSONResponseBodySuccessFalse PostContainerStop401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStop401JSONResponseBodySuccess enum.
func (e PostContainerStop401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStop401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStop403JSONResponseBodySuccess.
const (
	PostContainerStop403JSONResponseBodySuccessFalse PostContainerStop403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStop403JSONResponseBodySuccess enum.
func (e PostContainerStop403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStop403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStop404JSONResponseBodySuccess.
const (
	PostContainerStop404JSONResponseBodySuccessFalse PostContainerStop404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStop404JSONResponseBodySuccess enum.
func (e PostContainerStop404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStop404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStop409JSONResponseBodySuccess.
const (
	PostContainerStop409JSONResponseBodySuccessFalse PostContainerStop409JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStop409JSONResponseBodySuccess enum.
func (e PostContainerStop409JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStop409JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostContainerStop500JSONResponseBodySuccess.
const (
	PostContainerStop500JSONResponseBodySuccessFalse PostContainerStop500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostContainerStop500JSONResponseBodySuccess enum.
func (e PostContainerStop500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostContainerStop500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// GetContainersParams defines parameters for GetContainers.
type GetContainersParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetContainers200JSONResponseBodyDataItemsPortsType defines parameters for GetContainers.
type GetContainers200JSONResponseBodyDataItemsPortsType string

// GetContainers200JSONResponseBodyDataItemsState defines parameters for GetContainers.
type GetContainers200JSONResponseBodyDataItemsState string

// GetContainers200JSONResponseBodyDataRuntimeStatus defines parameters for GetContainers.
type GetContainers200JSONResponseBodyDataRuntimeStatus string

// GetContainers401JSONResponseBodySuccess defines parameters for GetContainers.
type GetContainers401JSONResponseBodySuccess bool

// GetContainers403JSONResponseBodySuccess defines parameters for GetContainers.
type GetContainers403JSONResponseBodySuccess bool

// GetContainers500JSONResponseBodySuccess defines parameters for GetContainers.
type GetContainers500JSONResponseBodySuccess bool

// GetContainerParams defines parameters for GetContainer.
type GetContainerParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetContainer200JSONResponseBodyDataPortsType defines parameters for GetContainer.
type GetContainer200JSONResponseBodyDataPortsType string

// GetContainer200JSONResponseBodyDataRuntimeInfoStatus defines parameters for GetContainer.
type GetContainer200JSONResponseBodyDataRuntimeInfoStatus string

// GetContainer200JSONResponseBodyDataState defines parameters for GetContainer.
type GetContainer200JSONResponseBodyDataState string

// GetContainer400JSONResponseBodySuccess defines parameters for GetContainer.
type GetContainer400JSONResponseBodySuccess bool

// GetContainer401JSONResponseBodySuccess defines parameters for GetContainer.
type GetContainer401JSONResponseBodySuccess bool

// GetContainer403JSONResponseBodySuccess defines parameters for GetContainer.
type GetContainer403JSONResponseBodySuccess bool

// GetContainer404JSONResponseBodySuccess defines parameters for GetContainer.
type GetContainer404JSONResponseBodySuccess bool

// GetContainer500JSONResponseBodySuccess defines parameters for GetContainer.
type GetContainer500JSONResponseBodySuccess bool

// GetContainerLogsParams defines parameters for GetContainerLogs.
type GetContainerLogsParams struct {
	// Tail Number of log lines to return from the end of the stream.
	Tail *int `form:"tail,omitempty" json:"tail,omitempty"`

	// Since Optional log lower bound. Accepts an RFC3339 timestamp or a duration such as 10m, 1h, or 24h. Invalid values must return a localized validation error.
	Since *string `form:"since,omitempty" json:"since,omitempty"`

	// Timestamps Whether each returned log line should include the runtime-provided timestamp.
	Timestamps *bool `form:"timestamps,omitempty" json:"timestamps,omitempty"`

	// Stdout Whether stdout stream lines should be included.
	Stdout *bool `form:"stdout,omitempty" json:"stdout,omitempty"`

	// Stderr Whether stderr stream lines should be included.
	Stderr *bool `form:"stderr,omitempty" json:"stderr,omitempty"`

	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetContainerLogs400JSONResponseBodySuccess defines parameters for GetContainerLogs.
type GetContainerLogs400JSONResponseBodySuccess bool

// GetContainerLogs401JSONResponseBodySuccess defines parameters for GetContainerLogs.
type GetContainerLogs401JSONResponseBodySuccess bool

// GetContainerLogs403JSONResponseBodySuccess defines parameters for GetContainerLogs.
type GetContainerLogs403JSONResponseBodySuccess bool

// GetContainerLogs404JSONResponseBodySuccess defines parameters for GetContainerLogs.
type GetContainerLogs404JSONResponseBodySuccess bool

// GetContainerLogs500JSONResponseBodySuccess defines parameters for GetContainerLogs.
type GetContainerLogs500JSONResponseBodySuccess bool

// PostContainerRestartParams defines parameters for PostContainerRestart.
type PostContainerRestartParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostContainerRestart200JSONResponseBodyDataAction defines parameters for PostContainerRestart.
type PostContainerRestart200JSONResponseBodyDataAction string

// PostContainerRestart200JSONResponseBodyDataResult defines parameters for PostContainerRestart.
type PostContainerRestart200JSONResponseBodyDataResult string

// PostContainerRestart400JSONResponseBodySuccess defines parameters for PostContainerRestart.
type PostContainerRestart400JSONResponseBodySuccess bool

// PostContainerRestart401JSONResponseBodySuccess defines parameters for PostContainerRestart.
type PostContainerRestart401JSONResponseBodySuccess bool

// PostContainerRestart403JSONResponseBodySuccess defines parameters for PostContainerRestart.
type PostContainerRestart403JSONResponseBodySuccess bool

// PostContainerRestart404JSONResponseBodySuccess defines parameters for PostContainerRestart.
type PostContainerRestart404JSONResponseBodySuccess bool

// PostContainerRestart409JSONResponseBodySuccess defines parameters for PostContainerRestart.
type PostContainerRestart409JSONResponseBodySuccess bool

// PostContainerRestart500JSONResponseBodySuccess defines parameters for PostContainerRestart.
type PostContainerRestart500JSONResponseBodySuccess bool

// PostContainerStartParams defines parameters for PostContainerStart.
type PostContainerStartParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostContainerStart200JSONResponseBodyDataAction defines parameters for PostContainerStart.
type PostContainerStart200JSONResponseBodyDataAction string

// PostContainerStart200JSONResponseBodyDataResult defines parameters for PostContainerStart.
type PostContainerStart200JSONResponseBodyDataResult string

// PostContainerStart400JSONResponseBodySuccess defines parameters for PostContainerStart.
type PostContainerStart400JSONResponseBodySuccess bool

// PostContainerStart401JSONResponseBodySuccess defines parameters for PostContainerStart.
type PostContainerStart401JSONResponseBodySuccess bool

// PostContainerStart403JSONResponseBodySuccess defines parameters for PostContainerStart.
type PostContainerStart403JSONResponseBodySuccess bool

// PostContainerStart404JSONResponseBodySuccess defines parameters for PostContainerStart.
type PostContainerStart404JSONResponseBodySuccess bool

// PostContainerStart409JSONResponseBodySuccess defines parameters for PostContainerStart.
type PostContainerStart409JSONResponseBodySuccess bool

// PostContainerStart500JSONResponseBodySuccess defines parameters for PostContainerStart.
type PostContainerStart500JSONResponseBodySuccess bool

// PostContainerStopParams defines parameters for PostContainerStop.
type PostContainerStopParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostContainerStop200JSONResponseBodyDataAction defines parameters for PostContainerStop.
type PostContainerStop200JSONResponseBodyDataAction string

// PostContainerStop200JSONResponseBodyDataResult defines parameters for PostContainerStop.
type PostContainerStop200JSONResponseBodyDataResult string

// PostContainerStop400JSONResponseBodySuccess defines parameters for PostContainerStop.
type PostContainerStop400JSONResponseBodySuccess bool

// PostContainerStop401JSONResponseBodySuccess defines parameters for PostContainerStop.
type PostContainerStop401JSONResponseBodySuccess bool

// PostContainerStop403JSONResponseBodySuccess defines parameters for PostContainerStop.
type PostContainerStop403JSONResponseBodySuccess bool

// PostContainerStop404JSONResponseBodySuccess defines parameters for PostContainerStop.
type PostContainerStop404JSONResponseBodySuccess bool

// PostContainerStop409JSONResponseBodySuccess defines parameters for PostContainerStop.
type PostContainerStop409JSONResponseBodySuccess bool

// PostContainerStop500JSONResponseBodySuccess defines parameters for PostContainerStop.
type PostContainerStop500JSONResponseBodySuccess bool
