// Code generated by ent, DO NOT EDIT.

package refreshsession

import (
	"graft/server/modules/user/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldUserID, v))
}

// TokenID applies equality check predicate on the "token_id" field. It's identical to TokenIDEQ.
func TokenID(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldTokenID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldRevokedAt, v))
}

// ReplacedByTokenID applies equality check predicate on the "replaced_by_token_id" field. It's identical to ReplacedByTokenIDEQ.
func ReplacedByTokenID(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldReplacedByTokenID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldUserID, vs...))
}

// TokenIDEQ applies the EQ predicate on the "token_id" field.
func TokenIDEQ(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldTokenID, v))
}

// TokenIDNEQ applies the NEQ predicate on the "token_id" field.
func TokenIDNEQ(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldTokenID, v))
}

// TokenIDIn applies the In predicate on the "token_id" field.
func TokenIDIn(vs ...string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldTokenID, vs...))
}

// TokenIDNotIn applies the NotIn predicate on the "token_id" field.
func TokenIDNotIn(vs ...string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldTokenID, vs...))
}

// TokenIDGT applies the GT predicate on the "token_id" field.
func TokenIDGT(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldTokenID, v))
}

// TokenIDGTE applies the GTE predicate on the "token_id" field.
func TokenIDGTE(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldTokenID, v))
}

// TokenIDLT applies the LT predicate on the "token_id" field.
func TokenIDLT(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldTokenID, v))
}

// TokenIDLTE applies the LTE predicate on the "token_id" field.
func TokenIDLTE(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldTokenID, v))
}

// TokenIDContains applies the Contains predicate on the "token_id" field.
func TokenIDContains(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldContains(FieldTokenID, v))
}

// TokenIDHasPrefix applies the HasPrefix predicate on the "token_id" field.
func TokenIDHasPrefix(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldHasPrefix(FieldTokenID, v))
}

// TokenIDHasSuffix applies the HasSuffix predicate on the "token_id" field.
func TokenIDHasSuffix(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldHasSuffix(FieldTokenID, v))
}

// TokenIDEqualFold applies the EqualFold predicate on the "token_id" field.
func TokenIDEqualFold(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEqualFold(FieldTokenID, v))
}

// TokenIDContainsFold applies the ContainsFold predicate on the "token_id" field.
func TokenIDContainsFold(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldContainsFold(FieldTokenID, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldExpiresAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotNull(FieldRevokedAt))
}

// ReplacedByTokenIDEQ applies the EQ predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDEQ(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDNEQ applies the NEQ predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDNEQ(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDIn applies the In predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDIn(vs ...string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldReplacedByTokenID, vs...))
}

// ReplacedByTokenIDNotIn applies the NotIn predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDNotIn(vs ...string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldReplacedByTokenID, vs...))
}

// ReplacedByTokenIDGT applies the GT predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDGT(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDGTE applies the GTE predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDGTE(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDLT applies the LT predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDLT(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDLTE applies the LTE predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDLTE(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDContains applies the Contains predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDContains(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldContains(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDHasPrefix applies the HasPrefix predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDHasPrefix(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldHasPrefix(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDHasSuffix applies the HasSuffix predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDHasSuffix(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldHasSuffix(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDIsNil applies the IsNil predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDIsNil() predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIsNull(FieldReplacedByTokenID))
}

// ReplacedByTokenIDNotNil applies the NotNil predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDNotNil() predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotNull(FieldReplacedByTokenID))
}

// ReplacedByTokenIDEqualFold applies the EqualFold predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDEqualFold(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEqualFold(FieldReplacedByTokenID, v))
}

// ReplacedByTokenIDContainsFold applies the ContainsFold predicate on the "replaced_by_token_id" field.
func ReplacedByTokenIDContainsFold(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldContainsFold(FieldReplacedByTokenID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RefreshSession {
	return predicate.RefreshSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RefreshSession {
	return predicate.RefreshSession(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RefreshSession) predicate.RefreshSession {
	return predicate.RefreshSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RefreshSession) predicate.RefreshSession {
	return predicate.RefreshSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RefreshSession) predicate.RefreshSession {
	return predicate.RefreshSession(sql.NotPredicates(p))
}
