// Package dashboardopenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package dashboardopenapi

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetDashboardSummary200JSONResponseBodyDataWidgetsCategory.
const (
	GetDashboardSummary200JSONResponseBodyDataWidgetsCategoryBusiness  GetDashboardSummary200JSONResponseBodyDataWidgetsCategory = "business"
	GetDashboardSummary200JSONResponseBodyDataWidgetsCategoryOperation GetDashboardSummary200JSONResponseBodyDataWidgetsCategory = "operation"
	GetDashboardSummary200JSONResponseBodyDataWidgetsCategorySecurity  GetDashboardSummary200JSONResponseBodyDataWidgetsCategory = "security"
	GetDashboardSummary200JSONResponseBodyDataWidgetsCategorySystem    GetDashboardSummary200JSONResponseBodyDataWidgetsCategory = "system"
)

// Valid indicates whether the value is a known member of the GetDashboardSummary200JSONResponseBodyDataWidgetsCategory enum.
func (e GetDashboardSummary200JSONResponseBodyDataWidgetsCategory) Valid() bool {
	switch e {
	case GetDashboardSummary200JSONResponseBodyDataWidgetsCategoryBusiness:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsCategoryOperation:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsCategorySecurity:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsCategorySystem:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardSummary200JSONResponseBodyDataWidgetsPriority.
const (
	GetDashboardSummary200JSONResponseBodyDataWidgetsPriorityCritical GetDashboardSummary200JSONResponseBodyDataWidgetsPriority = "critical"
	GetDashboardSummary200JSONResponseBodyDataWidgetsPriorityInfo     GetDashboardSummary200JSONResponseBodyDataWidgetsPriority = "info"
	GetDashboardSummary200JSONResponseBodyDataWidgetsPriorityNormal   GetDashboardSummary200JSONResponseBodyDataWidgetsPriority = "normal"
	GetDashboardSummary200JSONResponseBodyDataWidgetsPriorityWarning  GetDashboardSummary200JSONResponseBodyDataWidgetsPriority = "warning"
)

// Valid indicates whether the value is a known member of the GetDashboardSummary200JSONResponseBodyDataWidgetsPriority enum.
func (e GetDashboardSummary200JSONResponseBodyDataWidgetsPriority) Valid() bool {
	switch e {
	case GetDashboardSummary200JSONResponseBodyDataWidgetsPriorityCritical:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsPriorityInfo:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsPriorityNormal:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsPriorityWarning:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardSummary200JSONResponseBodyDataWidgetsSize.
const (
	GetDashboardSummary200JSONResponseBodyDataWidgetsSizeLarge  GetDashboardSummary200JSONResponseBodyDataWidgetsSize = "large"
	GetDashboardSummary200JSONResponseBodyDataWidgetsSizeMedium GetDashboardSummary200JSONResponseBodyDataWidgetsSize = "medium"
	GetDashboardSummary200JSONResponseBodyDataWidgetsSizeSmall  GetDashboardSummary200JSONResponseBodyDataWidgetsSize = "small"
)

// Valid indicates whether the value is a known member of the GetDashboardSummary200JSONResponseBodyDataWidgetsSize enum.
func (e GetDashboardSummary200JSONResponseBodyDataWidgetsSize) Valid() bool {
	switch e {
	case GetDashboardSummary200JSONResponseBodyDataWidgetsSizeLarge:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsSizeMedium:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsSizeSmall:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardSummary200JSONResponseBodyDataWidgetsState.
const (
	GetDashboardSummary200JSONResponseBodyDataWidgetsStateCritical GetDashboardSummary200JSONResponseBodyDataWidgetsState = "critical"
	GetDashboardSummary200JSONResponseBodyDataWidgetsStateHidden   GetDashboardSummary200JSONResponseBodyDataWidgetsState = "hidden"
	GetDashboardSummary200JSONResponseBodyDataWidgetsStateNormal   GetDashboardSummary200JSONResponseBodyDataWidgetsState = "normal"
	GetDashboardSummary200JSONResponseBodyDataWidgetsStateWarning  GetDashboardSummary200JSONResponseBodyDataWidgetsState = "warning"
)

// Valid indicates whether the value is a known member of the GetDashboardSummary200JSONResponseBodyDataWidgetsState enum.
func (e GetDashboardSummary200JSONResponseBodyDataWidgetsState) Valid() bool {
	switch e {
	case GetDashboardSummary200JSONResponseBodyDataWidgetsStateCritical:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsStateHidden:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsStateNormal:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsStateWarning:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardSummary200JSONResponseBodyDataWidgetsStatus.
const (
	GetDashboardSummary200JSONResponseBodyDataWidgetsStatusDisabled GetDashboardSummary200JSONResponseBodyDataWidgetsStatus = "disabled"
	GetDashboardSummary200JSONResponseBodyDataWidgetsStatusError    GetDashboardSummary200JSONResponseBodyDataWidgetsStatus = "error"
	GetDashboardSummary200JSONResponseBodyDataWidgetsStatusNormal   GetDashboardSummary200JSONResponseBodyDataWidgetsStatus = "normal"
	GetDashboardSummary200JSONResponseBodyDataWidgetsStatusWarning  GetDashboardSummary200JSONResponseBodyDataWidgetsStatus = "warning"
)

// Valid indicates whether the value is a known member of the GetDashboardSummary200JSONResponseBodyDataWidgetsStatus enum.
func (e GetDashboardSummary200JSONResponseBodyDataWidgetsStatus) Valid() bool {
	switch e {
	case GetDashboardSummary200JSONResponseBodyDataWidgetsStatusDisabled:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsStatusError:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsStatusNormal:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsStatusWarning:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardSummary200JSONResponseBodyDataWidgetsType.
const (
	GetDashboardSummary200JSONResponseBodyDataWidgetsTypeAlertList GetDashboardSummary200JSONResponseBodyDataWidgetsType = "alert-list"
	GetDashboardSummary200JSONResponseBodyDataWidgetsTypeHealth    GetDashboardSummary200JSONResponseBodyDataWidgetsType = "health"
	GetDashboardSummary200JSONResponseBodyDataWidgetsTypeLinkList  GetDashboardSummary200JSONResponseBodyDataWidgetsType = "link-list"
	GetDashboardSummary200JSONResponseBodyDataWidgetsTypeStatGroup GetDashboardSummary200JSONResponseBodyDataWidgetsType = "stat-group"
	GetDashboardSummary200JSONResponseBodyDataWidgetsTypeTimeline  GetDashboardSummary200JSONResponseBodyDataWidgetsType = "timeline"
)

// Valid indicates whether the value is a known member of the GetDashboardSummary200JSONResponseBodyDataWidgetsType enum.
func (e GetDashboardSummary200JSONResponseBodyDataWidgetsType) Valid() bool {
	switch e {
	case GetDashboardSummary200JSONResponseBodyDataWidgetsTypeAlertList:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsTypeHealth:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsTypeLinkList:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsTypeStatGroup:
		return true
	case GetDashboardSummary200JSONResponseBodyDataWidgetsTypeTimeline:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardSummary401JSONResponseBodySuccess.
const (
	GetDashboardSummary401JSONResponseBodySuccessFalse GetDashboardSummary401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetDashboardSummary401JSONResponseBodySuccess enum.
func (e GetDashboardSummary401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetDashboardSummary401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardSummary500JSONResponseBodySuccess.
const (
	GetDashboardSummary500JSONResponseBodySuccessFalse GetDashboardSummary500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetDashboardSummary500JSONResponseBodySuccess enum.
func (e GetDashboardSummary500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetDashboardSummary500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardWidget200JSONResponseBodyDataCategory.
const (
	GetDashboardWidget200JSONResponseBodyDataCategoryBusiness  GetDashboardWidget200JSONResponseBodyDataCategory = "business"
	GetDashboardWidget200JSONResponseBodyDataCategoryOperation GetDashboardWidget200JSONResponseBodyDataCategory = "operation"
	GetDashboardWidget200JSONResponseBodyDataCategorySecurity  GetDashboardWidget200JSONResponseBodyDataCategory = "security"
	GetDashboardWidget200JSONResponseBodyDataCategorySystem    GetDashboardWidget200JSONResponseBodyDataCategory = "system"
)

// Valid indicates whether the value is a known member of the GetDashboardWidget200JSONResponseBodyDataCategory enum.
func (e GetDashboardWidget200JSONResponseBodyDataCategory) Valid() bool {
	switch e {
	case GetDashboardWidget200JSONResponseBodyDataCategoryBusiness:
		return true
	case GetDashboardWidget200JSONResponseBodyDataCategoryOperation:
		return true
	case GetDashboardWidget200JSONResponseBodyDataCategorySecurity:
		return true
	case GetDashboardWidget200JSONResponseBodyDataCategorySystem:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardWidget200JSONResponseBodyDataPriority.
const (
	GetDashboardWidget200JSONResponseBodyDataPriorityCritical GetDashboardWidget200JSONResponseBodyDataPriority = "critical"
	GetDashboardWidget200JSONResponseBodyDataPriorityInfo     GetDashboardWidget200JSONResponseBodyDataPriority = "info"
	GetDashboardWidget200JSONResponseBodyDataPriorityNormal   GetDashboardWidget200JSONResponseBodyDataPriority = "normal"
	GetDashboardWidget200JSONResponseBodyDataPriorityWarning  GetDashboardWidget200JSONResponseBodyDataPriority = "warning"
)

// Valid indicates whether the value is a known member of the GetDashboardWidget200JSONResponseBodyDataPriority enum.
func (e GetDashboardWidget200JSONResponseBodyDataPriority) Valid() bool {
	switch e {
	case GetDashboardWidget200JSONResponseBodyDataPriorityCritical:
		return true
	case GetDashboardWidget200JSONResponseBodyDataPriorityInfo:
		return true
	case GetDashboardWidget200JSONResponseBodyDataPriorityNormal:
		return true
	case GetDashboardWidget200JSONResponseBodyDataPriorityWarning:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardWidget200JSONResponseBodyDataSize.
const (
	GetDashboardWidget200JSONResponseBodyDataSizeLarge  GetDashboardWidget200JSONResponseBodyDataSize = "large"
	GetDashboardWidget200JSONResponseBodyDataSizeMedium GetDashboardWidget200JSONResponseBodyDataSize = "medium"
	GetDashboardWidget200JSONResponseBodyDataSizeSmall  GetDashboardWidget200JSONResponseBodyDataSize = "small"
)

// Valid indicates whether the value is a known member of the GetDashboardWidget200JSONResponseBodyDataSize enum.
func (e GetDashboardWidget200JSONResponseBodyDataSize) Valid() bool {
	switch e {
	case GetDashboardWidget200JSONResponseBodyDataSizeLarge:
		return true
	case GetDashboardWidget200JSONResponseBodyDataSizeMedium:
		return true
	case GetDashboardWidget200JSONResponseBodyDataSizeSmall:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardWidget200JSONResponseBodyDataState.
const (
	GetDashboardWidget200JSONResponseBodyDataStateCritical GetDashboardWidget200JSONResponseBodyDataState = "critical"
	GetDashboardWidget200JSONResponseBodyDataStateHidden   GetDashboardWidget200JSONResponseBodyDataState = "hidden"
	GetDashboardWidget200JSONResponseBodyDataStateNormal   GetDashboardWidget200JSONResponseBodyDataState = "normal"
	GetDashboardWidget200JSONResponseBodyDataStateWarning  GetDashboardWidget200JSONResponseBodyDataState = "warning"
)

// Valid indicates whether the value is a known member of the GetDashboardWidget200JSONResponseBodyDataState enum.
func (e GetDashboardWidget200JSONResponseBodyDataState) Valid() bool {
	switch e {
	case GetDashboardWidget200JSONResponseBodyDataStateCritical:
		return true
	case GetDashboardWidget200JSONResponseBodyDataStateHidden:
		return true
	case GetDashboardWidget200JSONResponseBodyDataStateNormal:
		return true
	case GetDashboardWidget200JSONResponseBodyDataStateWarning:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardWidget200JSONResponseBodyDataStatus.
const (
	GetDashboardWidget200JSONResponseBodyDataStatusDisabled GetDashboardWidget200JSONResponseBodyDataStatus = "disabled"
	GetDashboardWidget200JSONResponseBodyDataStatusError    GetDashboardWidget200JSONResponseBodyDataStatus = "error"
	GetDashboardWidget200JSONResponseBodyDataStatusNormal   GetDashboardWidget200JSONResponseBodyDataStatus = "normal"
	GetDashboardWidget200JSONResponseBodyDataStatusWarning  GetDashboardWidget200JSONResponseBodyDataStatus = "warning"
)

// Valid indicates whether the value is a known member of the GetDashboardWidget200JSONResponseBodyDataStatus enum.
func (e GetDashboardWidget200JSONResponseBodyDataStatus) Valid() bool {
	switch e {
	case GetDashboardWidget200JSONResponseBodyDataStatusDisabled:
		return true
	case GetDashboardWidget200JSONResponseBodyDataStatusError:
		return true
	case GetDashboardWidget200JSONResponseBodyDataStatusNormal:
		return true
	case GetDashboardWidget200JSONResponseBodyDataStatusWarning:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardWidget200JSONResponseBodyDataType.
const (
	GetDashboardWidget200JSONResponseBodyDataTypeAlertList GetDashboardWidget200JSONResponseBodyDataType = "alert-list"
	GetDashboardWidget200JSONResponseBodyDataTypeHealth    GetDashboardWidget200JSONResponseBodyDataType = "health"
	GetDashboardWidget200JSONResponseBodyDataTypeLinkList  GetDashboardWidget200JSONResponseBodyDataType = "link-list"
	GetDashboardWidget200JSONResponseBodyDataTypeStatGroup GetDashboardWidget200JSONResponseBodyDataType = "stat-group"
	GetDashboardWidget200JSONResponseBodyDataTypeTimeline  GetDashboardWidget200JSONResponseBodyDataType = "timeline"
)

// Valid indicates whether the value is a known member of the GetDashboardWidget200JSONResponseBodyDataType enum.
func (e GetDashboardWidget200JSONResponseBodyDataType) Valid() bool {
	switch e {
	case GetDashboardWidget200JSONResponseBodyDataTypeAlertList:
		return true
	case GetDashboardWidget200JSONResponseBodyDataTypeHealth:
		return true
	case GetDashboardWidget200JSONResponseBodyDataTypeLinkList:
		return true
	case GetDashboardWidget200JSONResponseBodyDataTypeStatGroup:
		return true
	case GetDashboardWidget200JSONResponseBodyDataTypeTimeline:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardWidget401JSONResponseBodySuccess.
const (
	GetDashboardWidget401JSONResponseBodySuccessFalse GetDashboardWidget401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetDashboardWidget401JSONResponseBodySuccess enum.
func (e GetDashboardWidget401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetDashboardWidget401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardWidget404JSONResponseBodySuccess.
const (
	GetDashboardWidget404JSONResponseBodySuccessFalse GetDashboardWidget404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetDashboardWidget404JSONResponseBodySuccess enum.
func (e GetDashboardWidget404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetDashboardWidget404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetDashboardWidget500JSONResponseBodySuccess.
const (
	False GetDashboardWidget500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetDashboardWidget500JSONResponseBodySuccess enum.
func (e GetDashboardWidget500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// GetDashboardSummaryParams defines parameters for GetDashboardSummary.
type GetDashboardSummaryParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetDashboardSummary200JSONResponseBodyDataWidgetsCategory defines parameters for GetDashboardSummary.
type GetDashboardSummary200JSONResponseBodyDataWidgetsCategory string

// GetDashboardSummary200JSONResponseBodyDataWidgetsPriority defines parameters for GetDashboardSummary.
type GetDashboardSummary200JSONResponseBodyDataWidgetsPriority string

// GetDashboardSummary200JSONResponseBodyDataWidgetsSize defines parameters for GetDashboardSummary.
type GetDashboardSummary200JSONResponseBodyDataWidgetsSize string

// GetDashboardSummary200JSONResponseBodyDataWidgetsState defines parameters for GetDashboardSummary.
type GetDashboardSummary200JSONResponseBodyDataWidgetsState string

// GetDashboardSummary200JSONResponseBodyDataWidgetsStatus defines parameters for GetDashboardSummary.
type GetDashboardSummary200JSONResponseBodyDataWidgetsStatus string

// GetDashboardSummary200JSONResponseBodyDataWidgetsType defines parameters for GetDashboardSummary.
type GetDashboardSummary200JSONResponseBodyDataWidgetsType string

// GetDashboardSummary401JSONResponseBodySuccess defines parameters for GetDashboardSummary.
type GetDashboardSummary401JSONResponseBodySuccess bool

// GetDashboardSummary500JSONResponseBodySuccess defines parameters for GetDashboardSummary.
type GetDashboardSummary500JSONResponseBodySuccess bool

// GetDashboardWidgetParams defines parameters for GetDashboardWidget.
type GetDashboardWidgetParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetDashboardWidget200JSONResponseBodyDataCategory defines parameters for GetDashboardWidget.
type GetDashboardWidget200JSONResponseBodyDataCategory string

// GetDashboardWidget200JSONResponseBodyDataPriority defines parameters for GetDashboardWidget.
type GetDashboardWidget200JSONResponseBodyDataPriority string

// GetDashboardWidget200JSONResponseBodyDataSize defines parameters for GetDashboardWidget.
type GetDashboardWidget200JSONResponseBodyDataSize string

// GetDashboardWidget200JSONResponseBodyDataState defines parameters for GetDashboardWidget.
type GetDashboardWidget200JSONResponseBodyDataState string

// GetDashboardWidget200JSONResponseBodyDataStatus defines parameters for GetDashboardWidget.
type GetDashboardWidget200JSONResponseBodyDataStatus string

// GetDashboardWidget200JSONResponseBodyDataType defines parameters for GetDashboardWidget.
type GetDashboardWidget200JSONResponseBodyDataType string

// GetDashboardWidget401JSONResponseBodySuccess defines parameters for GetDashboardWidget.
type GetDashboardWidget401JSONResponseBodySuccess bool

// GetDashboardWidget404JSONResponseBodySuccess defines parameters for GetDashboardWidget.
type GetDashboardWidget404JSONResponseBodySuccess bool

// GetDashboardWidget500JSONResponseBodySuccess defines parameters for GetDashboardWidget.
type GetDashboardWidget500JSONResponseBodySuccess bool
