COMMENT ON TABLE "audit_policy_rules" IS '审计策略规则表（审计插件）';
COMMENT ON COLUMN "audit_policy_rules"."id" IS '主键 ID';
COMMENT ON COLUMN "audit_policy_rules"."name" IS '规则唯一名称';
COMMENT ON COLUMN "audit_policy_rules"."description" IS '规则说明';
COMMENT ON COLUMN "audit_policy_rules"."source" IS '规则来源类型，如请求、领域事件或安全事件';
COMMENT ON COLUMN "audit_policy_rules"."enabled" IS '规则是否启用';
COMMENT ON COLUMN "audit_policy_rules"."priority" IS '规则优先级，值越小越先匹配';
COMMENT ON COLUMN "audit_policy_rules"."effect" IS '规则生效方式，如纳入或排除审计';
COMMENT ON COLUMN "audit_policy_rules"."match_type" IS '路径或事件匹配方式，如精确或前缀';
COMMENT ON COLUMN "audit_policy_rules"."method" IS '匹配的 HTTP 方法，为空表示不限制';
COMMENT ON COLUMN "audit_policy_rules"."path_pattern" IS '匹配的请求路径或路径前缀';
COMMENT ON COLUMN "audit_policy_rules"."event_type" IS '匹配的领域事件或安全事件类型';
COMMENT ON COLUMN "audit_policy_rules"."risk_level" IS '命中的风险等级，为空表示不限制';
COMMENT ON COLUMN "audit_policy_rules"."target_type" IS '命中的目标资源类型，为空表示不限制';
COMMENT ON COLUMN "audit_policy_rules"."condition_expr" IS '扩展匹配条件表达式，为空表示无附加条件';
COMMENT ON COLUMN "audit_policy_rules"."created_at" IS '创建时间';
COMMENT ON COLUMN "audit_policy_rules"."updated_at" IS '最后更新时间';
