// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RefreshSessionsColumns holds the columns for the "refresh_sessions" table.
	RefreshSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_id", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "replaced_by_token_id", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// RefreshSessionsTable holds the schema information for the "refresh_sessions" table.
	RefreshSessionsTable = &schema.Table{
		Name:       "refresh_sessions",
		Columns:    RefreshSessionsColumns,
		PrimaryKey: []*schema.Column{RefreshSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "refresh_sessions_users_refresh_sessions",
				Columns:    []*schema.Column{RefreshSessionsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "refreshsession_user_id",
				Unique:  false,
				Columns: []*schema.Column{RefreshSessionsColumns[7]},
			},
			{
				Name:    "refreshsession_expires_at",
				Unique:  false,
				Columns: []*schema.Column{RefreshSessionsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "display", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "must_change_password", Type: field.TypeBool, Default: false},
		{Name: "password_changed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RefreshSessionsTable,
		UsersTable,
	}
)

func init() {
	RefreshSessionsTable.ForeignKeys[0].RefTable = UsersTable
	RefreshSessionsTable.Annotation = &entsql.Annotation{
		Table: "refresh_sessions",
	}
}
