// Code generated by ent, DO NOT EDIT.

package ent

import (
	"graft/server/internal/ent/auditlog"
	"graft/server/internal/ent/permission"
	"graft/server/internal/ent/refreshsession"
	"graft/server/internal/ent/role"
	"graft/server/internal/ent/rolepermission"
	"graft/server/internal/ent/schema"
	"graft/server/internal/ent/user"
	"graft/server/internal/ent/userrole"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescOperatorName is the schema descriptor for operator_name field.
	auditlogDescOperatorName := auditlogFields[1].Descriptor()
	// auditlog.DefaultOperatorName holds the default value on creation for the operator_name field.
	auditlog.DefaultOperatorName = auditlogDescOperatorName.Default.(string)
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[2].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescResourceType is the schema descriptor for resource_type field.
	auditlogDescResourceType := auditlogFields[3].Descriptor()
	// auditlog.DefaultResourceType holds the default value on creation for the resource_type field.
	auditlog.DefaultResourceType = auditlogDescResourceType.Default.(string)
	// auditlogDescResourceID is the schema descriptor for resource_id field.
	auditlogDescResourceID := auditlogFields[4].Descriptor()
	// auditlog.DefaultResourceID holds the default value on creation for the resource_id field.
	auditlog.DefaultResourceID = auditlogDescResourceID.Default.(string)
	// auditlogDescRequestMethod is the schema descriptor for request_method field.
	auditlogDescRequestMethod := auditlogFields[5].Descriptor()
	// auditlog.DefaultRequestMethod holds the default value on creation for the request_method field.
	auditlog.DefaultRequestMethod = auditlogDescRequestMethod.Default.(string)
	// auditlogDescRequestPath is the schema descriptor for request_path field.
	auditlogDescRequestPath := auditlogFields[6].Descriptor()
	// auditlog.DefaultRequestPath holds the default value on creation for the request_path field.
	auditlog.DefaultRequestPath = auditlogDescRequestPath.Default.(string)
	// auditlogDescIP is the schema descriptor for ip field.
	auditlogDescIP := auditlogFields[7].Descriptor()
	// auditlog.DefaultIP holds the default value on creation for the ip field.
	auditlog.DefaultIP = auditlogDescIP.Default.(string)
	// auditlogDescUserAgent is the schema descriptor for user_agent field.
	auditlogDescUserAgent := auditlogFields[8].Descriptor()
	// auditlog.DefaultUserAgent holds the default value on creation for the user_agent field.
	auditlog.DefaultUserAgent = auditlogDescUserAgent.Default.(string)
	// auditlogDescSuccess is the schema descriptor for success field.
	auditlogDescSuccess := auditlogFields[9].Descriptor()
	// auditlog.DefaultSuccess holds the default value on creation for the success field.
	auditlog.DefaultSuccess = auditlogDescSuccess.Default.(bool)
	// auditlogDescErrorMessage is the schema descriptor for error_message field.
	auditlogDescErrorMessage := auditlogFields[10].Descriptor()
	// auditlog.DefaultErrorMessage holds the default value on creation for the error_message field.
	auditlog.DefaultErrorMessage = auditlogDescErrorMessage.Default.(string)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[11].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescCode is the schema descriptor for code field.
	permissionDescCode := permissionFields[0].Descriptor()
	// permission.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	permission.CodeValidator = func() func(string) error {
		validators := permissionDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescDisplay is the schema descriptor for display field.
	permissionDescDisplay := permissionFields[1].Descriptor()
	// permission.DisplayValidator is a validator for the "display" field. It is called by the builders before save.
	permission.DisplayValidator = permissionDescDisplay.Validators[0].(func(string) error)
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[3].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionFields[4].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	refreshsessionFields := schema.RefreshSession{}.Fields()
	_ = refreshsessionFields
	// refreshsessionDescTokenID is the schema descriptor for token_id field.
	refreshsessionDescTokenID := refreshsessionFields[1].Descriptor()
	// refreshsession.TokenIDValidator is a validator for the "token_id" field. It is called by the builders before save.
	refreshsession.TokenIDValidator = refreshsessionDescTokenID.Validators[0].(func(string) error)
	// refreshsessionDescCreatedAt is the schema descriptor for created_at field.
	refreshsessionDescCreatedAt := refreshsessionFields[5].Descriptor()
	// refreshsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshsession.DefaultCreatedAt = refreshsessionDescCreatedAt.Default.(func() time.Time)
	// refreshsessionDescUpdatedAt is the schema descriptor for updated_at field.
	refreshsessionDescUpdatedAt := refreshsessionFields[6].Descriptor()
	// refreshsession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refreshsession.DefaultUpdatedAt = refreshsessionDescUpdatedAt.Default.(func() time.Time)
	// refreshsession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refreshsession.UpdateDefaultUpdatedAt = refreshsessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescDisplay is the schema descriptor for display field.
	roleDescDisplay := roleFields[1].Descriptor()
	// role.DisplayValidator is a validator for the "display" field. It is called by the builders before save.
	role.DisplayValidator = roleDescDisplay.Validators[0].(func(string) error)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[3].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[4].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	rolepermissionFields := schema.RolePermission{}.Fields()
	_ = rolepermissionFields
	// rolepermissionDescCreatedAt is the schema descriptor for created_at field.
	rolepermissionDescCreatedAt := rolepermissionFields[2].Descriptor()
	// rolepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	rolepermission.DefaultCreatedAt = rolepermissionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescDisplay is the schema descriptor for display field.
	userDescDisplay := userFields[1].Descriptor()
	// user.DisplayValidator is a validator for the "display" field. It is called by the builders before save.
	user.DisplayValidator = userDescDisplay.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	userroleFields := schema.UserRole{}.Fields()
	_ = userroleFields
	// userroleDescCreatedAt is the schema descriptor for created_at field.
	userroleDescCreatedAt := userroleFields[2].Descriptor()
	// userrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	userrole.DefaultCreatedAt = userroleDescCreatedAt.Default.(func() time.Time)
}
