// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"graft/server/internal/ent/predicate"
	"graft/server/internal/ent/refreshsession"
	"graft/server/internal/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetDisplay sets the "display" field.
func (_u *UserUpdate) SetDisplay(v string) *UserUpdate {
	_u.mutation.SetDisplay(v)
	return _u
}

// SetNillableDisplay sets the "display" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDisplay(v *string) *UserUpdate {
	if v != nil {
		_u.SetDisplay(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *UserUpdate) ClearPasswordHash() *UserUpdate {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetMustChangePassword sets the "must_change_password" field.
func (_u *UserUpdate) SetMustChangePassword(v bool) *UserUpdate {
	_u.mutation.SetMustChangePassword(v)
	return _u
}

// SetNillableMustChangePassword sets the "must_change_password" field if the given value is not nil.
func (_u *UserUpdate) SetNillableMustChangePassword(v *bool) *UserUpdate {
	if v != nil {
		_u.SetMustChangePassword(*v)
	}
	return _u
}

// SetPasswordChangedAt sets the "password_changed_at" field.
func (_u *UserUpdate) SetPasswordChangedAt(v time.Time) *UserUpdate {
	_u.mutation.SetPasswordChangedAt(v)
	return _u
}

// SetNillablePasswordChangedAt sets the "password_changed_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordChangedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetPasswordChangedAt(*v)
	}
	return _u
}

// ClearPasswordChangedAt clears the value of the "password_changed_at" field.
func (_u *UserUpdate) ClearPasswordChangedAt() *UserUpdate {
	_u.mutation.ClearPasswordChangedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRefreshSessionIDs adds the "refresh_sessions" edge to the RefreshSession entity by IDs.
func (_u *UserUpdate) AddRefreshSessionIDs(ids ...int) *UserUpdate {
	_u.mutation.AddRefreshSessionIDs(ids...)
	return _u
}

// AddRefreshSessions adds the "refresh_sessions" edges to the RefreshSession entity.
func (_u *UserUpdate) AddRefreshSessions(v ...*RefreshSession) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRefreshSessionIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearRefreshSessions clears all "refresh_sessions" edges to the RefreshSession entity.
func (_u *UserUpdate) ClearRefreshSessions() *UserUpdate {
	_u.mutation.ClearRefreshSessions()
	return _u
}

// RemoveRefreshSessionIDs removes the "refresh_sessions" edge to RefreshSession entities by IDs.
func (_u *UserUpdate) RemoveRefreshSessionIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveRefreshSessionIDs(ids...)
	return _u
}

// RemoveRefreshSessions removes "refresh_sessions" edges to RefreshSession entities.
func (_u *UserUpdate) RemoveRefreshSessions(v ...*RefreshSession) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRefreshSessionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Display(); ok {
		if err := user.DisplayValidator(v); err != nil {
			return &ValidationError{Name: "display", err: fmt.Errorf(`ent: validator failed for field "User.display": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Display(); ok {
		_spec.SetField(user.FieldDisplay, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(user.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.MustChangePassword(); ok {
		_spec.SetField(user.FieldMustChangePassword, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PasswordChangedAt(); ok {
		_spec.SetField(user.FieldPasswordChangedAt, field.TypeTime, value)
	}
	if _u.mutation.PasswordChangedAtCleared() {
		_spec.ClearField(user.FieldPasswordChangedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RefreshSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshSessionsTable,
			Columns: []string{user.RefreshSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshsession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRefreshSessionsIDs(); len(nodes) > 0 && !_u.mutation.RefreshSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshSessionsTable,
			Columns: []string{user.RefreshSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefreshSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshSessionsTable,
			Columns: []string{user.RefreshSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetDisplay sets the "display" field.
func (_u *UserUpdateOne) SetDisplay(v string) *UserUpdateOne {
	_u.mutation.SetDisplay(v)
	return _u
}

// SetNillableDisplay sets the "display" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDisplay(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetDisplay(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *UserUpdateOne) ClearPasswordHash() *UserUpdateOne {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetMustChangePassword sets the "must_change_password" field.
func (_u *UserUpdateOne) SetMustChangePassword(v bool) *UserUpdateOne {
	_u.mutation.SetMustChangePassword(v)
	return _u
}

// SetNillableMustChangePassword sets the "must_change_password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableMustChangePassword(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetMustChangePassword(*v)
	}
	return _u
}

// SetPasswordChangedAt sets the "password_changed_at" field.
func (_u *UserUpdateOne) SetPasswordChangedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetPasswordChangedAt(v)
	return _u
}

// SetNillablePasswordChangedAt sets the "password_changed_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordChangedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordChangedAt(*v)
	}
	return _u
}

// ClearPasswordChangedAt clears the value of the "password_changed_at" field.
func (_u *UserUpdateOne) ClearPasswordChangedAt() *UserUpdateOne {
	_u.mutation.ClearPasswordChangedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRefreshSessionIDs adds the "refresh_sessions" edge to the RefreshSession entity by IDs.
func (_u *UserUpdateOne) AddRefreshSessionIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddRefreshSessionIDs(ids...)
	return _u
}

// AddRefreshSessions adds the "refresh_sessions" edges to the RefreshSession entity.
func (_u *UserUpdateOne) AddRefreshSessions(v ...*RefreshSession) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRefreshSessionIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearRefreshSessions clears all "refresh_sessions" edges to the RefreshSession entity.
func (_u *UserUpdateOne) ClearRefreshSessions() *UserUpdateOne {
	_u.mutation.ClearRefreshSessions()
	return _u
}

// RemoveRefreshSessionIDs removes the "refresh_sessions" edge to RefreshSession entities by IDs.
func (_u *UserUpdateOne) RemoveRefreshSessionIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveRefreshSessionIDs(ids...)
	return _u
}

// RemoveRefreshSessions removes "refresh_sessions" edges to RefreshSession entities.
func (_u *UserUpdateOne) RemoveRefreshSessions(v ...*RefreshSession) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRefreshSessionIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Display(); ok {
		if err := user.DisplayValidator(v); err != nil {
			return &ValidationError{Name: "display", err: fmt.Errorf(`ent: validator failed for field "User.display": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Display(); ok {
		_spec.SetField(user.FieldDisplay, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(user.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.MustChangePassword(); ok {
		_spec.SetField(user.FieldMustChangePassword, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PasswordChangedAt(); ok {
		_spec.SetField(user.FieldPasswordChangedAt, field.TypeTime, value)
	}
	if _u.mutation.PasswordChangedAtCleared() {
		_spec.ClearField(user.FieldPasswordChangedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RefreshSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshSessionsTable,
			Columns: []string{user.RefreshSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshsession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRefreshSessionsIDs(); len(nodes) > 0 && !_u.mutation.RefreshSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshSessionsTable,
			Columns: []string{user.RefreshSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefreshSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RefreshSessionsTable,
			Columns: []string{user.RefreshSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
