// Copyright (c) 2025-2026 GeWuYou
// SPDX-License-Identifier: Apache-2.0

import type {
  ThemeModeTokenState,
  ThemePresetDefinition,
  ThemeTokenDefinition,
  ThemeWorkbenchAuthorityPatch,
  ThemeWorkbenchGroupDefinition,
  ThemeWorkbenchScenarioPresetDefinition,
  ThemeWorkbenchStylePatch,
} from '@/types/theme';

export const DEFAULT_THEME_PRESET_ID = 'tdesign-default';

export const GRAFT_BASE_THEME_TOKENS: ThemeModeTokenState = {
  light: {
    '--td-bg-color-page': '#fafbfc',
    '--td-bg-color-container': '#ffffff',
    '--td-bg-color-container-hover': '#f5f7fa',
    '--td-bg-color-secondarycontainer': '#f7f9fb',
    '--td-bg-color-component': '#f3f6f9',
    '--td-text-color-primary': '#111827',
    '--td-text-color-secondary': '#4b5563',
    '--td-text-color-placeholder': '#8a94a6',
    '--td-text-color-disabled': '#b8c0cc',
    '--td-component-border': '#d9e0ea',
    '--td-component-stroke': '#e5eaf2',
    '--td-border-level-1-color': '#e8edf4',
    '--td-scrollbar-color': '#c7d0dc',
    '--graft-shell-bg': '#fafbfc',
    '--graft-shell-header-bg': '#ffffff',
    '--graft-shell-sidebar-bg': '#ffffff',
    '--graft-shell-content-bg': '#fafbfc',
    '--graft-shell-border-color': '#e5eaf2',
    '--graft-card-bg': '#ffffff',
    '--graft-card-bg-hover': '#f7f9fc',
    '--graft-card-border-color': '#e5eaf2',
    '--graft-card-elevated-bg': '#ffffff',
    '--graft-metric-value-color': 'var(--td-brand-color)',
    '--graft-chart-text-color': '#111827',
    '--graft-chart-placeholder-color': '#8a94a6',
    '--graft-chart-border-color': '#d9e0ea',
    '--graft-chart-container-color': '#ffffff',
    '--graft-monitor-cpu-color': '#2f6bff',
    '--graft-monitor-memory-color': '#168f6d',
    '--graft-monitor-load-color': '#c26a05',
    '--graft-monitor-runtime-alloc-color': '#6d5bd0',
    '--graft-monitor-runtime-heap-color': '#1f7fc9',
    '--graft-monitor-runtime-sys-color': '#a86a28',
    '--graft-monitor-goroutines-color': '#c73f80',
  },
  dark: {
    '--td-bg-color-page': '#0b1118',
    '--td-bg-color-container': '#151b24',
    '--td-bg-color-container-hover': '#1d2632',
    '--td-bg-color-secondarycontainer': '#121923',
    '--td-bg-color-component': '#1d2632',
    '--td-text-color-primary': '#f0f3f8',
    '--td-text-color-secondary': '#aeb8c7',
    '--td-text-color-placeholder': '#778397',
    '--td-text-color-disabled': '#5f6b7c',
    '--td-component-border': '#303b49',
    '--td-component-stroke': '#273241',
    '--td-border-level-1-color': '#273241',
    '--td-scrollbar-color': '#3a4655',
    '--graft-dark-sidebar-bg': '#0f1720',
    '--graft-dark-header-bg': '#151b24',
    '--graft-dark-page-bg': '#0b1118',
    '--graft-dark-card-bg': '#151b24',
    '--graft-dark-card-elevated-bg': '#171f2a',
    '--graft-dark-border-color': '#273241',
    '--graft-dark-header-button-hover-bg': 'rgba(255,255,255,0.06)',
    '--graft-dark-header-button-active-bg': 'color-mix(in srgb, var(--td-brand-color) 18%, transparent)',
    '--graft-shell-bg': 'var(--graft-dark-page-bg)',
    '--graft-shell-header-bg': 'var(--graft-dark-header-bg)',
    '--graft-shell-sidebar-bg': 'var(--graft-dark-sidebar-bg)',
    '--graft-shell-content-bg': 'var(--graft-dark-page-bg)',
    '--graft-shell-border-color': 'var(--graft-dark-border-color)',
    '--graft-card-bg': 'var(--graft-dark-card-bg)',
    '--graft-card-bg-hover': '#1d2632',
    '--graft-card-border-color': 'var(--graft-dark-border-color)',
    '--graft-card-elevated-bg': 'var(--graft-dark-card-elevated-bg)',
    '--graft-metric-value-color': 'var(--td-brand-color-6)',
    '--graft-chart-text-color': '#f0f3f8',
    '--graft-chart-placeholder-color': '#778397',
    '--graft-chart-border-color': '#303946',
    '--graft-chart-container-color': '#161b22',
    '--graft-monitor-cpu-color': '#7aa2ff',
    '--graft-monitor-memory-color': '#4fd1a5',
    '--graft-monitor-load-color': '#ffb347',
    '--graft-monitor-runtime-alloc-color': '#a78bfa',
    '--graft-monitor-runtime-heap-color': '#5ab0ff',
    '--graft-monitor-runtime-sys-color': '#f2a65a',
    '--graft-monitor-goroutines-color': '#ff70c4',
  },
};

export const THEME_WORKBENCH_GROUPS: ThemeWorkbenchGroupDefinition[] = [
  { key: 'overview', labelKey: 'layout.setting.workbench.groups.overview' },
  { key: 'appearance', labelKey: 'layout.setting.workbench.groups.appearance' },
  { key: 'layout', labelKey: 'layout.setting.workbench.groups.layout' },
  { key: 'typography', labelKey: 'layout.setting.workbench.groups.typography' },
  { key: 'style', labelKey: 'layout.setting.workbench.groups.style' },
  { key: 'advanced', labelKey: 'layout.setting.workbench.groups.advanced' },
];

export const THEME_TOKEN_DEFINITIONS: ThemeTokenDefinition[] = [
  {
    key: '--td-brand-color',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.primaryBrand',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-1',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale1',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-2',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale2',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-3',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale3',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-4',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale4',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-5',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale5',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-6',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale6',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-7',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale7',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-8',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale8',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-9',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale9',
    followsBrandColor: true,
  },
  {
    key: '--td-brand-color-10',
    group: 'brand',
    labelKey: 'layout.setting.workbench.tokenDefinitions.brandScale10',
    followsBrandColor: true,
  },
  { key: '--td-text-color-primary', group: 'text', labelKey: 'layout.setting.workbench.tokenDefinitions.primaryText' },
  {
    key: '--td-text-color-secondary',
    group: 'text',
    labelKey: 'layout.setting.workbench.tokenDefinitions.secondaryText',
  },
  {
    key: '--td-text-color-placeholder',
    group: 'text',
    labelKey: 'layout.setting.workbench.tokenDefinitions.placeholderText',
  },
  {
    key: '--td-bg-color-page',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.pageBackground',
  },
  {
    key: '--td-bg-color-container',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.containerBackground',
  },
  {
    key: '--td-bg-color-container-hover',
    group: 'background',
    labelKey: 'layout.setting.workbench.tokenDefinitions.containerHoverBackground',
  },
  {
    key: '--td-component-border',
    group: 'border',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentBorder',
  },
  {
    key: '--td-component-stroke',
    group: 'border',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentStroke',
  },
  {
    key: '--td-border-level-1-color',
    group: 'border',
    labelKey: 'layout.setting.workbench.tokenDefinitions.level1Border',
  },
  { key: '--td-scrollbar-color', group: 'border', labelKey: 'layout.setting.workbench.tokenDefinitions.scrollbar' },
  {
    key: '--td-success-color',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.successFeedback',
  },
  {
    key: '--td-error-color',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.errorFeedback',
  },
  {
    key: '--td-warning-color',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.warningFeedback',
  },
  { key: '--td-font-family', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.fontFamily' },
  {
    key: '--td-font-body-medium',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.bodyMedium',
  },
  {
    key: '--td-font-title-medium',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.titleMedium',
  },
  {
    key: '--td-font-title-large',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.titleLarge',
  },
  { key: '--td-radius-small', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.smallRadius' },
  {
    key: '--td-radius-default',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.defaultRadius',
  },
  {
    key: '--td-radius-medium',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.mediumRadius',
  },
  { key: '--td-radius-large', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.largeRadius' },
  {
    key: '--td-radius-extraLarge',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.extraLargeRadius',
  },
  {
    key: '--td-radius-circle',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.circleRadius',
  },
  { key: '--td-shadow-1', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.shadowLevel1' },
  { key: '--td-shadow-2', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.shadowLevel2' },
  { key: '--td-shadow-3', group: 'component', labelKey: 'layout.setting.workbench.tokenDefinitions.shadowLevel3' },
  {
    key: '--td-comp-size-xs',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentSizeXs',
  },
  {
    key: '--td-comp-size-s',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentSizeS',
  },
  {
    key: '--td-comp-size-m',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentSizeM',
  },
  {
    key: '--td-comp-size-l',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentSizeL',
  },
  {
    key: '--td-comp-size-xl',
    group: 'component',
    labelKey: 'layout.setting.workbench.tokenDefinitions.componentSizeXl',
  },
];

const SIDE_LAYOUT_STYLE_PATCH: ThemeWorkbenchStylePatch = {
  layout: 'side',
  splitMenu: false,
  isSidebarFixed: true,
  isUseTabsRouter: false,
  showFooter: true,
  showHeader: true,
  showBreadcrumb: false,
  menuAutoCollapsed: false,
};

const MIX_LAYOUT_STYLE_PATCH: ThemeWorkbenchStylePatch = {
  layout: 'mix',
  splitMenu: true,
  isSidebarFixed: true,
  isUseTabsRouter: true,
  showFooter: true,
  showHeader: true,
  showBreadcrumb: false,
  menuAutoCollapsed: false,
};

const STANDARD_SYSTEM_AUTHORITY_PATCH: ThemeWorkbenchAuthorityPatch = {
  fontFamilyPreset: 'system',
  fontSizePreset: 'standard',
  radiusPreset: 'standard',
  shadowPreset: 'standard',
  densityPreset: 'standard',
};

const SOURCE_HAN_ROUNDED_AUTHORITY_PATCH: ThemeWorkbenchAuthorityPatch = {
  fontFamilyPreset: 'source-han-sans',
  fontSizePreset: 'standard',
  radiusPreset: 'rounded',
  shadowPreset: 'standard',
  densityPreset: 'comfortable',
};

// 推荐主题保持为纯前端本地配置，先服务当前工作台预览，不与后端契约耦合。
export const THEME_PRESET_DEFINITIONS: ThemePresetDefinition[] = [
  {
    id: 'tdesign-default',
    labelKey: 'layout.setting.workbench.presets.tdesignDefault.label',
    descriptionKey: 'layout.setting.workbench.presets.tdesignDefault.description',
    brandTheme: '#0052D9',
    authorityPatch: STANDARD_SYSTEM_AUTHORITY_PATCH,
    stylePatch: SIDE_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'tencent-cloud',
    labelKey: 'layout.setting.workbench.presets.tencentCloud.label',
    descriptionKey: 'layout.setting.workbench.presets.tencentCloud.description',
    brandTheme: '#0064FF',
    authorityPatch: {
      fontFamilyPreset: 'inter',
      fontSizePreset: 'standard',
      radiusPreset: 'business',
      shadowPreset: 'standard',
      densityPreset: 'standard',
    },
    stylePatch: MIX_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'mountain-green',
    labelKey: 'layout.setting.workbench.presets.mountainGreen.label',
    descriptionKey: 'layout.setting.workbench.presets.mountainGreen.description',
    brandTheme: '#2BA471',
    authorityPatch: SOURCE_HAN_ROUNDED_AUTHORITY_PATCH,
    stylePatch: SIDE_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'midnight-blue',
    labelKey: 'layout.setting.workbench.presets.midnightBlue.label',
    descriptionKey: 'layout.setting.workbench.presets.midnightBlue.description',
    brandTheme: '#3B82F6',
    mode: 'dark',
    authorityPatch: {
      fontFamilyPreset: 'harmonyos',
      fontSizePreset: 'standard',
      radiusPreset: 'standard',
      shadowPreset: 'floating',
      densityPreset: 'comfortable',
    },
    stylePatch: MIX_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'graphite-slate',
    labelKey: 'layout.setting.workbench.presets.graphiteSlate.label',
    descriptionKey: 'layout.setting.workbench.presets.graphiteSlate.description',
    brandTheme: '#4F6B8A',
    mode: 'dark',
    authorityPatch: {
      fontFamilyPreset: 'inter',
      fontSizePreset: 'small',
      radiusPreset: 'business',
      shadowPreset: 'flat',
      densityPreset: 'compact',
    },
    stylePatch: {
      layout: 'side',
      splitMenu: false,
      isSidebarFixed: true,
      isUseTabsRouter: true,
      showFooter: true,
      showHeader: true,
      showBreadcrumb: false,
      menuAutoCollapsed: true,
    },
  },
  {
    id: 'sunset-amber',
    labelKey: 'layout.setting.workbench.presets.sunsetAmber.label',
    descriptionKey: 'layout.setting.workbench.presets.sunsetAmber.description',
    brandTheme: '#D97706',
    authorityPatch: {
      mode: 'light',
      fontFamilyPreset: 'source-han-sans',
      fontSizePreset: 'standard',
      radiusPreset: 'rounded',
      shadowPreset: 'standard',
      densityPreset: 'comfortable',
    },
    stylePatch: SIDE_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'ocean-teal',
    labelKey: 'layout.setting.workbench.presets.oceanTeal.label',
    descriptionKey: 'layout.setting.workbench.presets.oceanTeal.description',
    brandTheme: '#0F8A83',
    authorityPatch: {
      mode: 'light',
      fontFamilyPreset: 'harmonyos',
      fontSizePreset: 'standard',
      radiusPreset: 'standard',
      shadowPreset: 'floating',
      densityPreset: 'standard',
    },
    stylePatch: MIX_LAYOUT_STYLE_PATCH,
  },
  {
    id: 'frost-silver',
    labelKey: 'layout.setting.workbench.presets.frostSilver.label',
    descriptionKey: 'layout.setting.workbench.presets.frostSilver.description',
    brandTheme: '#7A8CA5',
    authorityPatch: {
      mode: 'light',
      fontFamilyPreset: 'system',
      fontSizePreset: 'large',
      radiusPreset: 'capsule',
      shadowPreset: 'flat',
      densityPreset: 'comfortable',
    },
    stylePatch: {
      layout: 'side',
      splitMenu: false,
      isSidebarFixed: true,
      isUseTabsRouter: false,
      showFooter: true,
      showHeader: true,
      showBreadcrumb: false,
      menuAutoCollapsed: false,
    },
  },
];

export const THEME_WORKBENCH_SCENARIO_PRESETS: ThemeWorkbenchScenarioPresetDefinition[] = [
  {
    id: 'ops-wide',
    labelKey: 'layout.setting.workbench.scenarios.opsWide.label',
    descriptionKey: 'layout.setting.workbench.scenarios.opsWide.description',
    authorityPatch: {
      densityPreset: 'compact',
      shadowPreset: 'standard',
      radiusPreset: 'standard',
    },
    stylePatch: {
      layout: 'mix',
      splitMenu: true,
      isSidebarFixed: true,
      isUseTabsRouter: true,
    },
  },
  {
    id: 'night-watch',
    labelKey: 'layout.setting.workbench.scenarios.nightWatch.label',
    descriptionKey: 'layout.setting.workbench.scenarios.nightWatch.description',
    presetId: 'midnight-blue',
    authorityPatch: {
      mode: 'dark',
      densityPreset: 'comfortable',
      shadowPreset: 'flat',
    },
  },
  {
    id: 'low-distraction',
    labelKey: 'layout.setting.workbench.scenarios.lowDistraction.label',
    descriptionKey: 'layout.setting.workbench.scenarios.lowDistraction.description',
    authorityPatch: {
      mode: 'light',
      densityPreset: 'standard',
      shadowPreset: 'flat',
    },
    stylePatch: {
      showFooter: false,
    },
  },
  {
    id: 'high-density',
    labelKey: 'layout.setting.workbench.scenarios.highDensity.label',
    descriptionKey: 'layout.setting.workbench.scenarios.highDensity.description',
    authorityPatch: {
      densityPreset: 'compact',
      fontSizePreset: 'small',
    },
    stylePatch: {
      layout: 'side',
      splitMenu: false,
      showFooter: false,
    },
  },
];
