// Code generated by go generate; DO NOT EDIT.
package moduleregistry

import (
	"graft/server/internal/module"
	auditmodule "graft/server/modules/audit"
	authmodule "graft/server/modules/auth"
	monitormodule "graft/server/modules/monitor"
	rbacmodule "graft/server/modules/rbac"
	schedulermodule "graft/server/modules/scheduler"
	usermodule "graft/server/modules/user"
)

var generatedModuleSpecs = []module.Spec{
	auditmodule.NewModuleSpec(),
	authmodule.NewModuleSpec(),
	monitormodule.NewModuleSpec(),
	rbacmodule.NewModuleSpec(),
	schedulermodule.NewModuleSpec(),
	usermodule.NewModuleSpec(),
}
