// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"graft/server/plugins/user/ent/refreshsession"
	"graft/server/plugins/user/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 刷新令牌会话表（用户插件）
type RefreshSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 所属用户 ID
	UserID int `json:"user_id,omitempty"`
	// 刷新令牌唯一标识
	TokenID string `json:"token_id,omitempty"`
	// 过期时间
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// 撤销时间，为空表示未撤销
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// 轮换后替换当前令牌的新令牌 ID
	ReplacedByTokenID *string `json:"replaced_by_token_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RefreshSessionQuery when eager-loading is set.
	Edges        RefreshSessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RefreshSessionEdges holds the relations/edges for other nodes in the graph.
type RefreshSessionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RefreshSessionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RefreshSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case refreshsession.FieldID, refreshsession.FieldUserID:
			values[i] = new(sql.NullInt64)
		case refreshsession.FieldTokenID, refreshsession.FieldReplacedByTokenID:
			values[i] = new(sql.NullString)
		case refreshsession.FieldExpiresAt, refreshsession.FieldRevokedAt, refreshsession.FieldCreatedAt, refreshsession.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RefreshSession fields.
func (_m *RefreshSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case refreshsession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case refreshsession.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case refreshsession.FieldTokenID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_id", values[i])
			} else if value.Valid {
				_m.TokenID = value.String
			}
		case refreshsession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case refreshsession.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case refreshsession.FieldReplacedByTokenID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field replaced_by_token_id", values[i])
			} else if value.Valid {
				_m.ReplacedByTokenID = new(string)
				*_m.ReplacedByTokenID = value.String
			}
		case refreshsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case refreshsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RefreshSession.
// This includes values selected through modifiers, order, etc.
func (_m *RefreshSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the RefreshSession entity.
func (_m *RefreshSession) QueryUser() *UserQuery {
	return NewRefreshSessionClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this RefreshSession.
// Note that you need to call RefreshSession.Unwrap() before calling this method if this RefreshSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RefreshSession) Update() *RefreshSessionUpdateOne {
	return NewRefreshSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RefreshSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RefreshSession) Unwrap() *RefreshSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RefreshSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RefreshSession) String() string {
	var builder strings.Builder
	builder.WriteString("RefreshSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("token_id=")
	builder.WriteString(_m.TokenID)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReplacedByTokenID; v != nil {
		builder.WriteString("replaced_by_token_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RefreshSessions is a parsable slice of RefreshSession.
type RefreshSessions []*RefreshSession
