export const RBAC_API_PATH = {
  ROLES: '/api/roles',
  PERMISSIONS: '/api/permissions',
  ROLE_DETAIL_TEMPLATE: '/api/roles/{id}',
  ROLE_STATUS_TEMPLATE: '/api/roles/{id}/status',
  ROLE_DELETE_TEMPLATE: '/api/roles/{id}/delete',
  ROLE_UPDATE_TEMPLATE: '/api/roles/{id}/update',
  ROLE_PERMISSIONS_TEMPLATE: '/api/roles/{id}/permissions',
  ROLE_PERMISSIONS_REPLACE_TEMPLATE: '/api/roles/{id}/permissions/replace',
  ROLE_PERMISSIONS_ADD_TEMPLATE: '/api/roles/{id}/permissions/add',
  ROLE_PERMISSIONS_REMOVE_TEMPLATE: '/api/roles/{id}/permissions/remove',
  PERMISSION_DETAIL_TEMPLATE: '/api/permissions/{id}',
  USER_ROLES_TEMPLATE: '/api/users/{id}/roles',
  USER_ROLES_REPLACE_TEMPLATE: '/api/users/{id}/roles/replace',
  USER_ROLES_ADD_TEMPLATE: '/api/users/{id}/roles/add',
  USER_ROLES_REMOVE_TEMPLATE: '/api/users/{id}/roles/remove',
  USERS_ROLES_REPLACE: '/api/users/roles/replace',
  USERS_ROLES_ADD: '/api/users/roles/add',
  USERS_ROLES_REMOVE: '/api/users/roles/remove',
  ROLE_DETAIL: (roleId: number) => `/api/roles/${roleId}`,
  ROLE_STATUS: (roleId: number) => `/api/roles/${roleId}/status`,
  ROLE_DELETE: (roleId: number) => `/api/roles/${roleId}/delete`,
  ROLE_UPDATE: (roleId: number) => `/api/roles/${roleId}/update`,
  ROLE_PERMISSIONS: (roleId: number) => `/api/roles/${roleId}/permissions`,
  ROLE_PERMISSIONS_REPLACE: (roleId: number) => `/api/roles/${roleId}/permissions/replace`,
  ROLE_PERMISSIONS_ADD: (roleId: number) => `/api/roles/${roleId}/permissions/add`,
  ROLE_PERMISSIONS_REMOVE: (roleId: number) => `/api/roles/${roleId}/permissions/remove`,
  PERMISSION_DETAIL: (permissionId: number) => `/api/permissions/${permissionId}`,
  USER_ROLES: (userId: number) => `/api/users/${userId}/roles`,
  USER_ROLES_REPLACE: (userId: number) => `/api/users/${userId}/roles/replace`,
  USER_ROLES_ADD: (userId: number) => `/api/users/${userId}/roles/add`,
  USER_ROLES_REMOVE: (userId: number) => `/api/users/${userId}/roles/remove`,
} as const;
