// Code generated by ent, DO NOT EDIT.

package ent

import (
	"graft/server/modules/user/ent/refreshsession"
	"graft/server/modules/user/ent/schema"
	"graft/server/modules/user/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	refreshsessionFields := schema.RefreshSession{}.Fields()
	_ = refreshsessionFields
	// refreshsessionDescTokenID is the schema descriptor for token_id field.
	refreshsessionDescTokenID := refreshsessionFields[1].Descriptor()
	// refreshsession.TokenIDValidator is a validator for the "token_id" field. It is called by the builders before save.
	refreshsession.TokenIDValidator = refreshsessionDescTokenID.Validators[0].(func(string) error)
	// refreshsessionDescCreatedAt is the schema descriptor for created_at field.
	refreshsessionDescCreatedAt := refreshsessionFields[5].Descriptor()
	// refreshsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshsession.DefaultCreatedAt = refreshsessionDescCreatedAt.Default.(func() time.Time)
	// refreshsessionDescUpdatedAt is the schema descriptor for updated_at field.
	refreshsessionDescUpdatedAt := refreshsessionFields[6].Descriptor()
	// refreshsession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refreshsession.DefaultUpdatedAt = refreshsessionDescUpdatedAt.Default.(func() time.Time)
	// refreshsession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refreshsession.UpdateDefaultUpdatedAt = refreshsessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescDisplay is the schema descriptor for display field.
	userDescDisplay := userFields[1].Descriptor()
	// user.DisplayValidator is a validator for the "display" field. It is called by the builders before save.
	user.DisplayValidator = userDescDisplay.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[2].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	// userDescMustChangePassword is the schema descriptor for must_change_password field.
	userDescMustChangePassword := userFields[4].Descriptor()
	// user.DefaultMustChangePassword holds the default value on creation for the must_change_password field.
	user.DefaultMustChangePassword = userDescMustChangePassword.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescCreatedBy is the schema descriptor for created_by field.
	userDescCreatedBy := userFields[7].Descriptor()
	// user.DefaultCreatedBy holds the default value on creation for the created_by field.
	user.DefaultCreatedBy = userDescCreatedBy.Default.(uint64)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUpdatedBy is the schema descriptor for updated_by field.
	userDescUpdatedBy := userFields[9].Descriptor()
	// user.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	user.DefaultUpdatedBy = userDescUpdatedBy.Default.(uint64)
	// userDescDeletedAt is the schema descriptor for deleted_at field.
	userDescDeletedAt := userFields[10].Descriptor()
	// user.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	user.DefaultDeletedAt = userDescDeletedAt.Default.(int64)
	// userDescDeletedBy is the schema descriptor for deleted_by field.
	userDescDeletedBy := userFields[11].Descriptor()
	// user.DefaultDeletedBy holds the default value on creation for the deleted_by field.
	user.DefaultDeletedBy = userDescDeletedBy.Default.(uint64)
}
