ALTER TABLE "users"
  ADD COLUMN "password_hash" character varying NULL,
  ADD COLUMN "password_changed_at" timestamptz NULL;

CREATE TABLE "roles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" character varying NOT NULL,
  "display" character varying NOT NULL,
  "description" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "roles_name_key" ON "roles" ("name");

CREATE TABLE "permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" character varying NOT NULL,
  "display" character varying NOT NULL,
  "description" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "permissions_code_key" ON "permissions" ("code");

CREATE TABLE "refresh_sessions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "token_id" character varying NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz NULL,
  "replaced_by_token_id" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "refresh_sessions_users_refresh_sessions"
    FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE UNIQUE INDEX "refresh_sessions_token_id_key" ON "refresh_sessions" ("token_id");
CREATE INDEX "refreshsession_user_id" ON "refresh_sessions" ("user_id");
CREATE INDEX "refreshsession_expires_at" ON "refresh_sessions" ("expires_at");

CREATE TABLE "user_roles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamptz NOT NULL,
  "role_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_roles_roles_user_roles"
    FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "user_roles_users_user_roles"
    FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE UNIQUE INDEX "userrole_user_id_role_id" ON "user_roles" ("user_id", "role_id");
CREATE INDEX "userrole_role_id" ON "user_roles" ("role_id");

CREATE TABLE "role_permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamptz NOT NULL,
  "permission_id" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "role_permissions_permissions_role_permissions"
    FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "role_permissions_roles_role_permissions"
    FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE UNIQUE INDEX "rolepermission_role_id_permission_id" ON "role_permissions" ("role_id", "permission_id");
CREATE INDEX "rolepermission_permission_id" ON "role_permissions" ("permission_id");
