CREATE TABLE "audit_logs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "operator_id" bigint NULL,
  "operator_name" character varying NOT NULL DEFAULT '',
  "action" character varying NOT NULL,
  "resource_type" character varying NOT NULL DEFAULT '',
  "resource_id" character varying NOT NULL DEFAULT '',
  "request_method" character varying NOT NULL DEFAULT '',
  "request_path" character varying NOT NULL DEFAULT '',
  "ip" character varying NOT NULL DEFAULT '',
  "user_agent" character varying NOT NULL DEFAULT '',
  "success" boolean NOT NULL DEFAULT false,
  "error_message" character varying NOT NULL DEFAULT '',
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "auditlog_created_at" ON "audit_logs" ("created_at");
CREATE INDEX "auditlog_action" ON "audit_logs" ("action");
CREATE INDEX "auditlog_operator_id" ON "audit_logs" ("operator_id");
