// Package main generates the compile-time plugin registry artifact.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

const (
	modulePath         = "graft/server"
	pluginRegistryRoot = "internal/pluginregistry"
	pluginsDirName     = "plugins"
	descriptorFile     = "descriptor.go"
	generatedFileName  = "generated.go"
	generatedFilePerm  = 0o600
)

type pluginPackage struct {
	importAlias string
	importPath  string
}

func main() {
	workdir, err := os.Getwd()
	if err != nil {
		failf("resolve working directory: %v", err)
	}

	pluginsRoot := filepath.Clean(filepath.Join(workdir, "..", "..", pluginsDirName))
	packages, err := collectPluginPackages(pluginsRoot)
	if err != nil {
		failf("collect plugin packages: %v", err)
	}

	content, err := renderGeneratedFile(packages)
	if err != nil {
		failf("render generated file: %v", err)
	}

	outputPath := filepath.Join(workdir, generatedFileName)
	if err := os.WriteFile(outputPath, content, generatedFilePerm); err != nil {
		failf("write generated file: %v", err)
	}
}

func collectPluginPackages(pluginsRoot string) ([]pluginPackage, error) {
	entries, err := os.ReadDir(pluginsRoot)
	if err != nil {
		return nil, err
	}

	packages := make([]pluginPackage, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		name := strings.TrimSpace(entry.Name())
		if name == "" || strings.HasPrefix(name, ".") {
			continue
		}

		pluginDir := filepath.Join(pluginsRoot, name)
		if !fileExists(filepath.Join(pluginDir, descriptorFile)) {
			return nil, fmt.Errorf("plugin package %s is missing %s", name, descriptorFile)
		}

		packages = append(packages, pluginPackage{
			importAlias: sanitizeImportAlias(name) + "plugin",
			importPath:  modulePath + "/" + filepath.ToSlash(filepath.Join(pluginsDirName, name)),
		})
	}

	sort.Slice(packages, func(left int, right int) bool {
		return packages[left].importPath < packages[right].importPath
	})
	return packages, nil
}

func renderGeneratedFile(packages []pluginPackage) ([]byte, error) {
	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	buffer.WriteString("package pluginregistry\n\n")
	buffer.WriteString("import (\n")
	buffer.WriteString("\t\"graft/server/internal/plugin\"\n")
	for _, current := range packages {
		_, _ = fmt.Fprintf(&buffer, "\t%s %q\n", current.importAlias, current.importPath)
	}
	buffer.WriteString(")\n\n")
	buffer.WriteString("var generatedDescriptors = []plugin.Descriptor{\n")
	for _, current := range packages {
		_, _ = fmt.Fprintf(&buffer, "\t%s.NewDescriptor(),\n", current.importAlias)
	}
	buffer.WriteString("}\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, err
	}

	return formatted, nil
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func sanitizeImportAlias(name string) string {
	var builder strings.Builder
	for _, current := range name {
		current = unicode.ToLower(current)
		if (current >= 'a' && current <= 'z') || (current >= '0' && current <= '9') {
			builder.WriteRune(current)
		} else {
			builder.WriteRune('_')
		}
	}

	alias := strings.Trim(builder.String(), "_")
	if alias == "" {
		return "pluginpkg"
	}
	if alias[0] >= '0' && alias[0] <= '9' {
		return "pluginpkg_" + alias
	}

	return alias
}

func failf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
