package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	testDirPerm  = 0o750
	testFilePerm = 0o600
)

// TestCollectModulePackagesSortsDeterministically 验证生成输入会按稳定顺序排序。
func TestCollectModulePackagesSortsDeterministically(t *testing.T) {
	root := t.TempDir()
	for _, name := range []string{"user", "audit", "rbac"} {
		dir := filepath.Join(root, name)
		if err := os.MkdirAll(dir, testDirPerm); err != nil {
			t.Fatalf("mkdir %s: %v", dir, err)
		}
		if err := os.WriteFile(filepath.Join(dir, descriptorFile), []byte("package "+name+"\n"), testFilePerm); err != nil {
			t.Fatalf("write %s: %v", descriptorFile, err)
		}
	}

	packages, err := collectModulePackages(root)
	if err != nil {
		t.Fatalf("collect packages: %v", err)
	}

	if len(packages) != 3 {
		t.Fatalf("expected 3 packages, got %d", len(packages))
	}

	got := []string{packages[0].importPath, packages[1].importPath, packages[2].importPath}
	expected := []string{
		"graft/server/plugins/audit",
		"graft/server/plugins/rbac",
		"graft/server/plugins/user",
	}
	for index := range expected {
		if got[index] != expected[index] {
			t.Fatalf("expected %v, got %v", expected, got)
		}
	}
}

// TestCollectModulePackagesRejectsMissingDescriptor 验证缺少描述符接线文件会直接失败。
func TestCollectModulePackagesRejectsMissingDescriptor(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, "user")
	if err := os.MkdirAll(dir, testDirPerm); err != nil {
		t.Fatalf("mkdir plugin dir: %v", err)
	}

	_, err := collectModulePackages(root)
	if err == nil {
		t.Fatal("expected missing descriptor error")
	}
	if !strings.Contains(err.Error(), descriptorFile) {
		t.Fatalf("expected descriptor error, got %v", err)
	}
}

// TestRenderGeneratedFileIncludesSortedModuleSpecs 验证生成文件内容稳定且包含模块定义入口。
func TestRenderGeneratedFileIncludesSortedDescriptors(t *testing.T) {
	content, err := renderGeneratedFile([]modulePackage{
		{importAlias: "auditplugin", importPath: "graft/server/plugins/audit"},
		{importAlias: "userplugin", importPath: "graft/server/plugins/user"},
	})
	if err != nil {
		t.Fatalf("render generated file: %v", err)
	}

	source := string(content)
	for _, snippet := range []string{
		"// Code generated by go generate; DO NOT EDIT.",
		"package pluginregistry",
		"auditplugin \"graft/server/plugins/audit\"",
		"userplugin \"graft/server/plugins/user\"",
		"auditplugin.NewModuleSpec()",
		"userplugin.NewModuleSpec()",
	} {
		if !strings.Contains(source, snippet) {
			t.Fatalf("expected generated source to contain %q, got:\n%s", snippet, source)
		}
	}
	if strings.Index(source, "auditplugin.NewModuleSpec()") > strings.Index(source, "userplugin.NewModuleSpec()") {
		t.Fatalf("expected generated module specs to remain sorted, got:\n%s", source)
	}
}
