// Code generated by ent, DO NOT EDIT.

package ent

import (
	"graft/server/plugins/rbac/ent/permission"
	"graft/server/plugins/rbac/ent/role"
	"graft/server/plugins/rbac/ent/rolepermission"
	"graft/server/plugins/rbac/ent/schema"
	"graft/server/plugins/rbac/ent/userrole"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescCode is the schema descriptor for code field.
	permissionDescCode := permissionFields[0].Descriptor()
	// permission.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	permission.CodeValidator = func() func(string) error {
		validators := permissionDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescDisplay is the schema descriptor for display field.
	permissionDescDisplay := permissionFields[1].Descriptor()
	// permission.DisplayValidator is a validator for the "display" field. It is called by the builders before save.
	permission.DisplayValidator = permissionDescDisplay.Validators[0].(func(string) error)
	// permissionDescCategory is the schema descriptor for category field.
	permissionDescCategory := permissionFields[3].Descriptor()
	// permission.DefaultCategory holds the default value on creation for the category field.
	permission.DefaultCategory = permissionDescCategory.Default.(string)
	// permission.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	permission.CategoryValidator = permissionDescCategory.Validators[0].(func(string) error)
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[4].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescCreatedBy is the schema descriptor for created_by field.
	permissionDescCreatedBy := permissionFields[5].Descriptor()
	// permission.DefaultCreatedBy holds the default value on creation for the created_by field.
	permission.DefaultCreatedBy = permissionDescCreatedBy.Default.(uint64)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionFields[6].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// permissionDescUpdatedBy is the schema descriptor for updated_by field.
	permissionDescUpdatedBy := permissionFields[7].Descriptor()
	// permission.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	permission.DefaultUpdatedBy = permissionDescUpdatedBy.Default.(uint64)
	// permissionDescDeletedAt is the schema descriptor for deleted_at field.
	permissionDescDeletedAt := permissionFields[8].Descriptor()
	// permission.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	permission.DefaultDeletedAt = permissionDescDeletedAt.Default.(int64)
	// permissionDescDeletedBy is the schema descriptor for deleted_by field.
	permissionDescDeletedBy := permissionFields[9].Descriptor()
	// permission.DefaultDeletedBy holds the default value on creation for the deleted_by field.
	permission.DefaultDeletedBy = permissionDescDeletedBy.Default.(uint64)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescDisplay is the schema descriptor for display field.
	roleDescDisplay := roleFields[1].Descriptor()
	// role.DisplayValidator is a validator for the "display" field. It is called by the builders before save.
	role.DisplayValidator = roleDescDisplay.Validators[0].(func(string) error)
	// roleDescBuiltin is the schema descriptor for builtin field.
	roleDescBuiltin := roleFields[3].Descriptor()
	// role.DefaultBuiltin holds the default value on creation for the builtin field.
	role.DefaultBuiltin = roleDescBuiltin.Default.(bool)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[4].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescCreatedBy is the schema descriptor for created_by field.
	roleDescCreatedBy := roleFields[5].Descriptor()
	// role.DefaultCreatedBy holds the default value on creation for the created_by field.
	role.DefaultCreatedBy = roleDescCreatedBy.Default.(uint64)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[6].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescUpdatedBy is the schema descriptor for updated_by field.
	roleDescUpdatedBy := roleFields[7].Descriptor()
	// role.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	role.DefaultUpdatedBy = roleDescUpdatedBy.Default.(uint64)
	// roleDescDeletedAt is the schema descriptor for deleted_at field.
	roleDescDeletedAt := roleFields[8].Descriptor()
	// role.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	role.DefaultDeletedAt = roleDescDeletedAt.Default.(int64)
	// roleDescDeletedBy is the schema descriptor for deleted_by field.
	roleDescDeletedBy := roleFields[9].Descriptor()
	// role.DefaultDeletedBy holds the default value on creation for the deleted_by field.
	role.DefaultDeletedBy = roleDescDeletedBy.Default.(uint64)
	rolepermissionMixin := schema.RolePermission{}.Mixin()
	rolepermissionMixinFields0 := rolepermissionMixin[0].Fields()
	_ = rolepermissionMixinFields0
	rolepermissionFields := schema.RolePermission{}.Fields()
	_ = rolepermissionFields
	// rolepermissionDescCreatedAt is the schema descriptor for created_at field.
	rolepermissionDescCreatedAt := rolepermissionMixinFields0[2].Descriptor()
	// rolepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	rolepermission.DefaultCreatedAt = rolepermissionDescCreatedAt.Default.(func() time.Time)
	userroleMixin := schema.UserRole{}.Mixin()
	userroleMixinFields0 := userroleMixin[0].Fields()
	_ = userroleMixinFields0
	userroleFields := schema.UserRole{}.Fields()
	_ = userroleFields
	// userroleDescCreatedAt is the schema descriptor for created_at field.
	userroleDescCreatedAt := userroleMixinFields0[2].Descriptor()
	// userrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	userrole.DefaultCreatedAt = userroleDescCreatedAt.Default.(func() time.Time)
}
