// Code generated by go generate; DO NOT EDIT.
package pluginregistry

import (
	"graft/server/internal/plugin"
	auditplugin "graft/server/plugins/audit"
	authplugin "graft/server/plugins/auth"
	monitorplugin "graft/server/plugins/monitor"
	rbacplugin "graft/server/plugins/rbac"
	schedulerplugin "graft/server/plugins/scheduler"
	userplugin "graft/server/plugins/user"
)

var generatedDescriptors = []plugin.Descriptor{
	auditplugin.NewDescriptor(),
	authplugin.NewDescriptor(),
	monitorplugin.NewDescriptor(),
	rbacplugin.NewDescriptor(),
	schedulerplugin.NewDescriptor(),
	userplugin.NewDescriptor(),
}
