// Code generated by go generate; DO NOT EDIT.
package pluginregistry

import (
	"graft/server/internal/plugin"
	auditplugin "graft/server/plugins/audit"
	authplugin "graft/server/plugins/auth"
	monitorplugin "graft/server/plugins/monitor"
	rbacplugin "graft/server/plugins/rbac"
	schedulerplugin "graft/server/plugins/scheduler"
	userplugin "graft/server/plugins/user"
)

var generatedModuleSpecs = []plugin.ModuleSpec{
	auditplugin.NewModuleSpec(),
	authplugin.NewModuleSpec(),
	monitorplugin.NewModuleSpec(),
	rbacplugin.NewModuleSpec(),
	schedulerplugin.NewModuleSpec(),
	userplugin.NewModuleSpec(),
}
