CREATE TABLE "scheduled_tasks" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_key" character varying NOT NULL,
  "job_key" character varying NOT NULL DEFAULT '',
  "title_key" character varying NOT NULL DEFAULT '',
  "title" character varying NOT NULL,
  "description_key" character varying NOT NULL DEFAULT '',
  "description" text NOT NULL DEFAULT '',
  "cron_expression" character varying NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "builtin" boolean NOT NULL DEFAULT false,
  "config_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "config_source" character varying NOT NULL DEFAULT 'system',
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW(),
  "deleted_at" bigint NOT NULL DEFAULT 0,
  CONSTRAINT "scheduled_tasks_title_not_blank" CHECK (btrim("title") <> ''),
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "scheduled_tasks_task_key_live_key"
  ON "scheduled_tasks" ("task_key")
  WHERE "deleted_at" = 0;
CREATE UNIQUE INDEX "scheduled_tasks_title_live_key"
  ON "scheduled_tasks" ("title")
  WHERE "deleted_at" = 0;
CREATE INDEX "scheduled_tasks_job_key" ON "scheduled_tasks" ("job_key");
CREATE INDEX "scheduled_tasks_enabled" ON "scheduled_tasks" ("enabled");
CREATE INDEX "scheduled_tasks_deleted_at" ON "scheduled_tasks" ("deleted_at");

CREATE TABLE "scheduler_job_definitions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "job_key" character varying NOT NULL,
  "module_key" character varying NOT NULL DEFAULT '',
  "category" character varying NOT NULL DEFAULT 'custom',
  "title_key" character varying NOT NULL DEFAULT '',
  "title" character varying NOT NULL DEFAULT '',
  "short_title_key" character varying NOT NULL DEFAULT '',
  "short_title" character varying NOT NULL DEFAULT '',
  "description_key" character varying NOT NULL DEFAULT '',
  "description" text NOT NULL DEFAULT '',
  "config_schema" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "default_config" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "default_cron" character varying NOT NULL DEFAULT '',
  "default_enabled" boolean NOT NULL DEFAULT false,
  "enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW(),
  "deleted_at" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "scheduler_job_definitions_job_key_live_key"
  ON "scheduler_job_definitions" ("job_key")
  WHERE "deleted_at" = 0;
CREATE INDEX "scheduler_job_definitions_module_key" ON "scheduler_job_definitions" ("module_key");
CREATE INDEX "scheduler_job_definitions_category" ON "scheduler_job_definitions" ("category");
CREATE INDEX "scheduler_job_definitions_enabled" ON "scheduler_job_definitions" ("enabled");
CREATE INDEX "scheduler_job_definitions_deleted_at" ON "scheduler_job_definitions" ("deleted_at");

CREATE TABLE "scheduler_task_runs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_key" character varying NOT NULL,
  "job_key" character varying NOT NULL DEFAULT '',
  "task_title" character varying NOT NULL DEFAULT '',
  "task_title_key" character varying NOT NULL DEFAULT '',
  "job_title" character varying NOT NULL DEFAULT '',
  "job_title_key" character varying NOT NULL DEFAULT '',
  "job_short_title" character varying NOT NULL DEFAULT '',
  "job_short_title_key" character varying NOT NULL DEFAULT '',
  "job_category" character varying NOT NULL DEFAULT 'custom',
  "module_key" character varying NOT NULL DEFAULT '',
  "task_builtin" boolean NOT NULL DEFAULT false,
  "trigger_type" character varying NOT NULL,
  "status" character varying NOT NULL,
  "result_summary" text NOT NULL DEFAULT '',
  "result_json" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "error_message" text NOT NULL DEFAULT '',
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz NULL,
  "duration_ms" bigint NULL,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE INDEX "scheduler_task_runs_task_key_started_at"
  ON "scheduler_task_runs" ("task_key", "started_at" DESC, "id" DESC);
CREATE INDEX "scheduler_task_runs_job_key" ON "scheduler_task_runs" ("job_key");
CREATE INDEX "scheduler_task_runs_status" ON "scheduler_task_runs" ("status");
CREATE INDEX "scheduler_task_runs_trigger_type" ON "scheduler_task_runs" ("trigger_type");

COMMENT ON TABLE "scheduled_tasks" IS 'Scheduled Task 调度实例表（scheduler 模块）';
COMMENT ON COLUMN "scheduled_tasks"."id" IS '主键 ID';
COMMENT ON COLUMN "scheduled_tasks"."task_key" IS 'Scheduled Task 实例稳定标识';
COMMENT ON COLUMN "scheduled_tasks"."job_key" IS '绑定的 Job Definition 稳定标识';
COMMENT ON COLUMN "scheduled_tasks"."title_key" IS '任务实例标题国际化键';
COMMENT ON COLUMN "scheduled_tasks"."title" IS '任务实例默认标题';
COMMENT ON COLUMN "scheduled_tasks"."description_key" IS '任务实例说明国际化键';
COMMENT ON COLUMN "scheduled_tasks"."description" IS '任务实例默认说明';
COMMENT ON COLUMN "scheduled_tasks"."cron_expression" IS '任务实例 cron 表达式';
COMMENT ON COLUMN "scheduled_tasks"."enabled" IS '任务实例是否启用调度';
COMMENT ON COLUMN "scheduled_tasks"."builtin" IS '是否为系统内置任务实例';
COMMENT ON COLUMN "scheduled_tasks"."config_json" IS '任务实例配置覆盖 JSON';
COMMENT ON COLUMN "scheduled_tasks"."config_source" IS '任务配置来源：system 表示使用 Job Definition 默认配置，user 表示用户显式覆盖配置';
COMMENT ON COLUMN "scheduled_tasks"."created_at" IS '创建时间';
COMMENT ON COLUMN "scheduled_tasks"."updated_at" IS '更新时间';
COMMENT ON COLUMN "scheduled_tasks"."deleted_at" IS '软删除时间戳，0 表示未删除，非 0 表示删除发生时的 Unix 秒';
COMMENT ON INDEX "scheduled_tasks_task_key_live_key" IS '活跃任务实例 task_key 唯一索引';
COMMENT ON INDEX "scheduled_tasks_title_live_key" IS '活跃任务实例标题唯一索引，软删除后允许复用标题';

COMMENT ON TABLE "scheduler_job_definitions" IS '可调度 Job Definition 表（scheduler 模块）';
COMMENT ON COLUMN "scheduler_job_definitions"."id" IS '主键 ID';
COMMENT ON COLUMN "scheduler_job_definitions"."job_key" IS 'Job Definition 稳定标识';
COMMENT ON COLUMN "scheduler_job_definitions"."module_key" IS '声明该 Job Definition 的模块标识';
COMMENT ON COLUMN "scheduler_job_definitions"."category" IS 'Job Definition 稳定分类，取值来自 scheduler job category typed contract';
COMMENT ON COLUMN "scheduler_job_definitions"."title_key" IS 'Job Definition 完整标题国际化键';
COMMENT ON COLUMN "scheduler_job_definitions"."title" IS 'Job Definition 默认完整标题';
COMMENT ON COLUMN "scheduler_job_definitions"."short_title_key" IS 'Job Definition 短标题国际化键';
COMMENT ON COLUMN "scheduler_job_definitions"."short_title" IS 'Job Definition 默认短标题';
COMMENT ON COLUMN "scheduler_job_definitions"."description_key" IS 'Job Definition 说明国际化键';
COMMENT ON COLUMN "scheduler_job_definitions"."description" IS 'Job Definition 默认说明';
COMMENT ON COLUMN "scheduler_job_definitions"."config_schema" IS 'Scheduled Task 配置 JSON Schema';
COMMENT ON COLUMN "scheduler_job_definitions"."default_config" IS '创建 Scheduled Task 时的默认配置 JSON';
COMMENT ON COLUMN "scheduler_job_definitions"."default_cron" IS '创建 Scheduled Task 时的默认 cron 表达式';
COMMENT ON COLUMN "scheduler_job_definitions"."default_enabled" IS '内置 Scheduled Task 初次种子任务是否默认启用';
COMMENT ON COLUMN "scheduler_job_definitions"."enabled" IS 'Job Definition 是否允许被创建或展示';
COMMENT ON COLUMN "scheduler_job_definitions"."created_at" IS '创建时间';
COMMENT ON COLUMN "scheduler_job_definitions"."updated_at" IS '更新时间';
COMMENT ON COLUMN "scheduler_job_definitions"."deleted_at" IS '软删除时间戳，0 表示未删除，非 0 表示删除发生时的 Unix 秒';
COMMENT ON INDEX "scheduler_job_definitions_job_key_live_key" IS '活跃 Job Definition job_key 唯一索引';

COMMENT ON TABLE "scheduler_task_runs" IS '定时任务运行历史表（scheduler 模块）';
COMMENT ON COLUMN "scheduler_task_runs"."id" IS '主键 ID';
COMMENT ON COLUMN "scheduler_task_runs"."task_key" IS '执行时 Scheduled Task 实例标识快照';
COMMENT ON COLUMN "scheduler_task_runs"."job_key" IS '执行时 Job Definition 标识快照';
COMMENT ON COLUMN "scheduler_task_runs"."task_title" IS '执行时任务实例标题快照';
COMMENT ON COLUMN "scheduler_task_runs"."task_title_key" IS '执行时任务实例标题国际化键快照';
COMMENT ON COLUMN "scheduler_task_runs"."job_title" IS '执行时 Job Definition 完整标题快照';
COMMENT ON COLUMN "scheduler_task_runs"."job_title_key" IS '执行时 Job Definition 标题国际化键快照';
COMMENT ON COLUMN "scheduler_task_runs"."job_short_title" IS '执行时 Job Definition 短标题快照';
COMMENT ON COLUMN "scheduler_task_runs"."job_short_title_key" IS '执行时 Job Definition 短标题国际化键快照';
COMMENT ON COLUMN "scheduler_task_runs"."job_category" IS '执行时 Job Definition 稳定分类快照';
COMMENT ON COLUMN "scheduler_task_runs"."module_key" IS '执行时 Job Definition 所属模块标识快照';
COMMENT ON COLUMN "scheduler_task_runs"."task_builtin" IS '执行时任务实例是否为系统内置任务快照';
COMMENT ON COLUMN "scheduler_task_runs"."trigger_type" IS '触发类型：cron、manual 或 startup';
COMMENT ON COLUMN "scheduler_task_runs"."status" IS '运行状态：running、success 或 failed';
COMMENT ON COLUMN "scheduler_task_runs"."result_summary" IS '运行结果摘要，不保存完整响应体';
COMMENT ON COLUMN "scheduler_task_runs"."result_json" IS '本次执行的结构化 JobRunResult JSON';
COMMENT ON COLUMN "scheduler_task_runs"."error_message" IS '失败错误摘要，为空表示无错误';
COMMENT ON COLUMN "scheduler_task_runs"."started_at" IS '运行开始时间';
COMMENT ON COLUMN "scheduler_task_runs"."finished_at" IS '运行结束时间';
COMMENT ON COLUMN "scheduler_task_runs"."duration_ms" IS '运行耗时毫秒数';
COMMENT ON COLUMN "scheduler_task_runs"."created_at" IS '记录创建时间';
