CREATE TABLE IF NOT EXISTS "scheduler_job_definitions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "job_key" character varying NOT NULL,
  "module_key" character varying NOT NULL DEFAULT '',
  "title_key" character varying NOT NULL DEFAULT '',
  "title" character varying NOT NULL DEFAULT '',
  "description_key" character varying NOT NULL DEFAULT '',
  "description" text NOT NULL DEFAULT '',
  "params_schema" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "default_params" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "default_cron" character varying NOT NULL DEFAULT '',
  "enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "scheduler_job_definitions_job_key_key" ON "scheduler_job_definitions" ("job_key");
CREATE INDEX IF NOT EXISTS "scheduler_job_definitions_module_key" ON "scheduler_job_definitions" ("module_key");
CREATE INDEX IF NOT EXISTS "scheduler_job_definitions_enabled" ON "scheduler_job_definitions" ("enabled");
CREATE INDEX IF NOT EXISTS "scheduler_job_definitions_deleted_at" ON "scheduler_job_definitions" ("deleted_at");

ALTER TABLE "scheduled_tasks"
  ADD COLUMN IF NOT EXISTS "job_key" character varying NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "module_key" character varying NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "params_json" jsonb NOT NULL DEFAULT '{}'::jsonb;

UPDATE "scheduled_tasks"
SET "job_key" = CASE WHEN "job_key" = '' THEN "task_key" ELSE "job_key" END,
    "module_key" = CASE WHEN "module_key" = '' THEN 'scheduler' ELSE "module_key" END,
    "params_json" = CASE WHEN "params_json" = '{}'::jsonb THEN "config_json" ELSE "params_json" END,
    "task_type" = 'job'
WHERE "deleted_at" IS NULL;

CREATE INDEX IF NOT EXISTS "scheduled_tasks_job_key" ON "scheduled_tasks" ("job_key");
CREATE INDEX IF NOT EXISTS "scheduled_tasks_module_key" ON "scheduled_tasks" ("module_key");

ALTER TABLE "scheduler_task_runs"
  ADD COLUMN IF NOT EXISTS "job_key" character varying NOT NULL DEFAULT '';

UPDATE "scheduler_task_runs"
SET "job_key" = CASE WHEN "job_key" = '' THEN "task_key" ELSE "job_key" END,
    "task_type" = 'job';

CREATE INDEX IF NOT EXISTS "scheduler_task_runs_job_key" ON "scheduler_task_runs" ("job_key");

COMMENT ON TABLE "scheduler_job_definitions" IS '可调度 Job Definition 表（scheduler 模块）';
COMMENT ON COLUMN "scheduler_job_definitions"."id" IS '主键 ID';
COMMENT ON COLUMN "scheduler_job_definitions"."job_key" IS 'Job Definition 稳定标识';
COMMENT ON COLUMN "scheduler_job_definitions"."module_key" IS '声明该 Job Definition 的模块标识';
COMMENT ON COLUMN "scheduler_job_definitions"."title_key" IS 'Job Definition 标题国际化键';
COMMENT ON COLUMN "scheduler_job_definitions"."title" IS 'Job Definition 默认标题';
COMMENT ON COLUMN "scheduler_job_definitions"."description_key" IS 'Job Definition 说明国际化键';
COMMENT ON COLUMN "scheduler_job_definitions"."description" IS 'Job Definition 默认说明';
COMMENT ON COLUMN "scheduler_job_definitions"."params_schema" IS 'Scheduled Task 参数 JSON Schema';
COMMENT ON COLUMN "scheduler_job_definitions"."default_params" IS '创建 Scheduled Task 时的默认参数 JSON';
COMMENT ON COLUMN "scheduler_job_definitions"."default_cron" IS '创建 Scheduled Task 时的默认 cron 表达式';
COMMENT ON COLUMN "scheduler_job_definitions"."enabled" IS 'Job Definition 是否允许被创建或展示';
COMMENT ON COLUMN "scheduler_job_definitions"."created_at" IS '创建时间';
COMMENT ON COLUMN "scheduler_job_definitions"."updated_at" IS '更新时间';
COMMENT ON COLUMN "scheduler_job_definitions"."deleted_at" IS '软删除时间，为空表示未删除';

COMMENT ON TABLE "scheduled_tasks" IS 'Scheduled Task 调度实例表（scheduler 模块）';
COMMENT ON COLUMN "scheduled_tasks"."task_key" IS 'Scheduled Task 稳定标识';
COMMENT ON COLUMN "scheduled_tasks"."job_key" IS '关联的 Job Definition 稳定标识';
COMMENT ON COLUMN "scheduled_tasks"."module_key" IS 'Job Definition 所属模块标识';
COMMENT ON COLUMN "scheduled_tasks"."task_type" IS '历史兼容列，当前固定为 job';
COMMENT ON COLUMN "scheduled_tasks"."params_json" IS '传递给 Job Definition handler 的参数 JSON';
COMMENT ON COLUMN "scheduled_tasks"."config_json" IS '历史兼容列，当前镜像 params_json';

COMMENT ON COLUMN "scheduler_task_runs"."job_key" IS '本次执行关联的 Job Definition 稳定标识';
COMMENT ON COLUMN "scheduler_task_runs"."task_type" IS '历史兼容列，当前固定为 job';
