// Package applogopenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package applogopenapi

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetAppLogsParamsSeverity.
const (
	GetAppLogsParamsSeverityDebug GetAppLogsParamsSeverity = "debug"
	GetAppLogsParamsSeverityError GetAppLogsParamsSeverity = "error"
	GetAppLogsParamsSeverityInfo  GetAppLogsParamsSeverity = "info"
	GetAppLogsParamsSeverityWarn  GetAppLogsParamsSeverity = "warn"
)

// Valid indicates whether the value is a known member of the GetAppLogsParamsSeverity enum.
func (e GetAppLogsParamsSeverity) Valid() bool {
	switch e {
	case GetAppLogsParamsSeverityDebug:
		return true
	case GetAppLogsParamsSeverityError:
		return true
	case GetAppLogsParamsSeverityInfo:
		return true
	case GetAppLogsParamsSeverityWarn:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogsParamsSort.
const (
	ComponentAsc   GetAppLogsParamsSort = "component:asc"
	ComponentDesc  GetAppLogsParamsSort = "component:desc"
	OccurredAtAsc  GetAppLogsParamsSort = "occurred_at:asc"
	OccurredAtDesc GetAppLogsParamsSort = "occurred_at:desc"
	SeverityAsc    GetAppLogsParamsSort = "severity:asc"
	SeverityDesc   GetAppLogsParamsSort = "severity:desc"
)

// Valid indicates whether the value is a known member of the GetAppLogsParamsSort enum.
func (e GetAppLogsParamsSort) Valid() bool {
	switch e {
	case ComponentAsc:
		return true
	case ComponentDesc:
		return true
	case OccurredAtAsc:
		return true
	case OccurredAtDesc:
		return true
	case SeverityAsc:
		return true
	case SeverityDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogs200JSONResponseBodyDataItemsSeverity.
const (
	GetAppLogs200JSONResponseBodyDataItemsSeverityDebug GetAppLogs200JSONResponseBodyDataItemsSeverity = "debug"
	GetAppLogs200JSONResponseBodyDataItemsSeverityError GetAppLogs200JSONResponseBodyDataItemsSeverity = "error"
	GetAppLogs200JSONResponseBodyDataItemsSeverityInfo  GetAppLogs200JSONResponseBodyDataItemsSeverity = "info"
	GetAppLogs200JSONResponseBodyDataItemsSeverityWarn  GetAppLogs200JSONResponseBodyDataItemsSeverity = "warn"
)

// Valid indicates whether the value is a known member of the GetAppLogs200JSONResponseBodyDataItemsSeverity enum.
func (e GetAppLogs200JSONResponseBodyDataItemsSeverity) Valid() bool {
	switch e {
	case GetAppLogs200JSONResponseBodyDataItemsSeverityDebug:
		return true
	case GetAppLogs200JSONResponseBodyDataItemsSeverityError:
		return true
	case GetAppLogs200JSONResponseBodyDataItemsSeverityInfo:
		return true
	case GetAppLogs200JSONResponseBodyDataItemsSeverityWarn:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogs400JSONResponseBodySuccess.
const (
	GetAppLogs400JSONResponseBodySuccessFalse GetAppLogs400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogs400JSONResponseBodySuccess enum.
func (e GetAppLogs400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogs400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogs401JSONResponseBodySuccess.
const (
	GetAppLogs401JSONResponseBodySuccessFalse GetAppLogs401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogs401JSONResponseBodySuccess enum.
func (e GetAppLogs401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogs401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogs403JSONResponseBodySuccess.
const (
	GetAppLogs403JSONResponseBodySuccessFalse GetAppLogs403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogs403JSONResponseBodySuccess enum.
func (e GetAppLogs403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogs403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogs500JSONResponseBodySuccess.
const (
	GetAppLogs500JSONResponseBodySuccessFalse GetAppLogs500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogs500JSONResponseBodySuccess enum.
func (e GetAppLogs500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogs500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogBatchDelete400JSONResponseBodySuccess.
const (
	PostAppLogBatchDelete400JSONResponseBodySuccessFalse PostAppLogBatchDelete400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogBatchDelete400JSONResponseBodySuccess enum.
func (e PostAppLogBatchDelete400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogBatchDelete400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogBatchDelete401JSONResponseBodySuccess.
const (
	PostAppLogBatchDelete401JSONResponseBodySuccessFalse PostAppLogBatchDelete401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogBatchDelete401JSONResponseBodySuccess enum.
func (e PostAppLogBatchDelete401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogBatchDelete401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogBatchDelete403JSONResponseBodySuccess.
const (
	PostAppLogBatchDelete403JSONResponseBodySuccessFalse PostAppLogBatchDelete403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogBatchDelete403JSONResponseBodySuccess enum.
func (e PostAppLogBatchDelete403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogBatchDelete403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogBatchDelete404JSONResponseBodySuccess.
const (
	PostAppLogBatchDelete404JSONResponseBodySuccessFalse PostAppLogBatchDelete404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogBatchDelete404JSONResponseBodySuccess enum.
func (e PostAppLogBatchDelete404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogBatchDelete404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostAppLogBatchDelete500JSONResponseBodySuccess.
const (
	PostAppLogBatchDelete500JSONResponseBodySuccessFalse PostAppLogBatchDelete500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostAppLogBatchDelete500JSONResponseBodySuccess enum.
func (e PostAppLogBatchDelete500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostAppLogBatchDelete500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for DeleteAppLog400JSONResponseBodySuccess.
const (
	DeleteAppLog400JSONResponseBodySuccessFalse DeleteAppLog400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the DeleteAppLog400JSONResponseBodySuccess enum.
func (e DeleteAppLog400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case DeleteAppLog400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for DeleteAppLog401JSONResponseBodySuccess.
const (
	DeleteAppLog401JSONResponseBodySuccessFalse DeleteAppLog401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the DeleteAppLog401JSONResponseBodySuccess enum.
func (e DeleteAppLog401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case DeleteAppLog401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for DeleteAppLog403JSONResponseBodySuccess.
const (
	DeleteAppLog403JSONResponseBodySuccessFalse DeleteAppLog403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the DeleteAppLog403JSONResponseBodySuccess enum.
func (e DeleteAppLog403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case DeleteAppLog403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for DeleteAppLog404JSONResponseBodySuccess.
const (
	DeleteAppLog404JSONResponseBodySuccessFalse DeleteAppLog404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the DeleteAppLog404JSONResponseBodySuccess enum.
func (e DeleteAppLog404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case DeleteAppLog404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for DeleteAppLog500JSONResponseBodySuccess.
const (
	DeleteAppLog500JSONResponseBodySuccessFalse DeleteAppLog500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the DeleteAppLog500JSONResponseBodySuccess enum.
func (e DeleteAppLog500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case DeleteAppLog500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail200JSONResponseBodyDataSeverity.
const (
	Debug GetAppLogDetail200JSONResponseBodyDataSeverity = "debug"
	Error GetAppLogDetail200JSONResponseBodyDataSeverity = "error"
	Info  GetAppLogDetail200JSONResponseBodyDataSeverity = "info"
	Warn  GetAppLogDetail200JSONResponseBodyDataSeverity = "warn"
)

// Valid indicates whether the value is a known member of the GetAppLogDetail200JSONResponseBodyDataSeverity enum.
func (e GetAppLogDetail200JSONResponseBodyDataSeverity) Valid() bool {
	switch e {
	case Debug:
		return true
	case Error:
		return true
	case Info:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail400JSONResponseBodySuccess.
const (
	GetAppLogDetail400JSONResponseBodySuccessFalse GetAppLogDetail400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogDetail400JSONResponseBodySuccess enum.
func (e GetAppLogDetail400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogDetail400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail401JSONResponseBodySuccess.
const (
	GetAppLogDetail401JSONResponseBodySuccessFalse GetAppLogDetail401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogDetail401JSONResponseBodySuccess enum.
func (e GetAppLogDetail401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogDetail401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail403JSONResponseBodySuccess.
const (
	GetAppLogDetail403JSONResponseBodySuccessFalse GetAppLogDetail403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogDetail403JSONResponseBodySuccess enum.
func (e GetAppLogDetail403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogDetail403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail404JSONResponseBodySuccess.
const (
	GetAppLogDetail404JSONResponseBodySuccessFalse GetAppLogDetail404JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogDetail404JSONResponseBodySuccess enum.
func (e GetAppLogDetail404JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetAppLogDetail404JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetAppLogDetail500JSONResponseBodySuccess.
const (
	False GetAppLogDetail500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetAppLogDetail500JSONResponseBodySuccess enum.
func (e GetAppLogDetail500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// refreshCookieContextKey is the context key for refreshCookie security scheme
type refreshCookieContextKey string

// GetAppLogsParams defines parameters for GetAppLogs.
type GetAppLogsParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// OccurredFrom Inclusive canonical occurrence-time lower bound on `occurred_at`.
	OccurredFrom *time.Time `form:"occurred_from,omitempty" json:"occurred_from,omitempty"`

	// OccurredTo Inclusive canonical occurrence-time upper bound on `occurred_at`.
	OccurredTo *time.Time                `form:"occurred_to,omitempty" json:"occurred_to,omitempty"`
	Severity   *GetAppLogsParamsSeverity `form:"severity,omitempty" json:"severity,omitempty"`
	Component  *string                   `form:"component,omitempty" json:"component,omitempty"`
	Operation  *string                   `form:"operation,omitempty" json:"operation,omitempty"`
	RequestId  *string                   `form:"request_id,omitempty" json:"request_id,omitempty"`
	TraceId    *string                   `form:"trace_id,omitempty" json:"trace_id,omitempty"`

	// Keyword Canonical fuzzy match applied to component, operation, message, and error.
	Keyword *string `form:"keyword,omitempty" json:"keyword,omitempty"`

	// Message Bounded fuzzy match applied to the app-log message only.
	Message *string `form:"message,omitempty" json:"message,omitempty"`

	// Error Bounded fuzzy match applied to the app-log error text only.
	Error *string `form:"error,omitempty" json:"error,omitempty"`

	// Sort Repeated sort fields encoded as `field:direction`.
	Sort *[]GetAppLogsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetAppLogsParamsSeverity defines parameters for GetAppLogs.
type GetAppLogsParamsSeverity string

// GetAppLogsParamsSort defines parameters for GetAppLogs.
type GetAppLogsParamsSort string

// GetAppLogs200JSONResponseBodyDataItemsSeverity defines parameters for GetAppLogs.
type GetAppLogs200JSONResponseBodyDataItemsSeverity string

// GetAppLogs400JSONResponseBodySuccess defines parameters for GetAppLogs.
type GetAppLogs400JSONResponseBodySuccess bool

// GetAppLogs401JSONResponseBodySuccess defines parameters for GetAppLogs.
type GetAppLogs401JSONResponseBodySuccess bool

// GetAppLogs403JSONResponseBodySuccess defines parameters for GetAppLogs.
type GetAppLogs403JSONResponseBodySuccess bool

// GetAppLogs500JSONResponseBodySuccess defines parameters for GetAppLogs.
type GetAppLogs500JSONResponseBodySuccess bool

// PostAppLogBatchDeleteJSONBody defines parameters for PostAppLogBatchDelete.
type PostAppLogBatchDeleteJSONBody struct {
	Ids []int64 `json:"ids"`
}

// PostAppLogBatchDeleteParams defines parameters for PostAppLogBatchDelete.
type PostAppLogBatchDeleteParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// PostAppLogBatchDelete400JSONResponseBodySuccess defines parameters for PostAppLogBatchDelete.
type PostAppLogBatchDelete400JSONResponseBodySuccess bool

// PostAppLogBatchDelete401JSONResponseBodySuccess defines parameters for PostAppLogBatchDelete.
type PostAppLogBatchDelete401JSONResponseBodySuccess bool

// PostAppLogBatchDelete403JSONResponseBodySuccess defines parameters for PostAppLogBatchDelete.
type PostAppLogBatchDelete403JSONResponseBodySuccess bool

// PostAppLogBatchDelete404JSONResponseBodySuccess defines parameters for PostAppLogBatchDelete.
type PostAppLogBatchDelete404JSONResponseBodySuccess bool

// PostAppLogBatchDelete500JSONResponseBodySuccess defines parameters for PostAppLogBatchDelete.
type PostAppLogBatchDelete500JSONResponseBodySuccess bool

// DeleteAppLogParams defines parameters for DeleteAppLog.
type DeleteAppLogParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// DeleteAppLog400JSONResponseBodySuccess defines parameters for DeleteAppLog.
type DeleteAppLog400JSONResponseBodySuccess bool

// DeleteAppLog401JSONResponseBodySuccess defines parameters for DeleteAppLog.
type DeleteAppLog401JSONResponseBodySuccess bool

// DeleteAppLog403JSONResponseBodySuccess defines parameters for DeleteAppLog.
type DeleteAppLog403JSONResponseBodySuccess bool

// DeleteAppLog404JSONResponseBodySuccess defines parameters for DeleteAppLog.
type DeleteAppLog404JSONResponseBodySuccess bool

// DeleteAppLog500JSONResponseBodySuccess defines parameters for DeleteAppLog.
type DeleteAppLog500JSONResponseBodySuccess bool

// GetAppLogDetailParams defines parameters for GetAppLogDetail.
type GetAppLogDetailParams struct {
	// XGraftLocale Explicit locale override header already supported by the runtime.
	XGraftLocale *string `json:"X-Graft-Locale,omitempty"`

	// XRequestId Optional caller-supplied request id. If omitted, the runtime generates one and echoes it
	// through the response header and envelope traceId field.
	XRequestId *string `json:"X-Request-Id,omitempty"`
}

// GetAppLogDetail200JSONResponseBodyDataSeverity defines parameters for GetAppLogDetail.
type GetAppLogDetail200JSONResponseBodyDataSeverity string

// GetAppLogDetail400JSONResponseBodySuccess defines parameters for GetAppLogDetail.
type GetAppLogDetail400JSONResponseBodySuccess bool

// GetAppLogDetail401JSONResponseBodySuccess defines parameters for GetAppLogDetail.
type GetAppLogDetail401JSONResponseBodySuccess bool

// GetAppLogDetail403JSONResponseBodySuccess defines parameters for GetAppLogDetail.
type GetAppLogDetail403JSONResponseBodySuccess bool

// GetAppLogDetail404JSONResponseBodySuccess defines parameters for GetAppLogDetail.
type GetAppLogDetail404JSONResponseBodySuccess bool

// GetAppLogDetail500JSONResponseBodySuccess defines parameters for GetAppLogDetail.
type GetAppLogDetail500JSONResponseBodySuccess bool

// PostAppLogBatchDeleteJSONRequestBody defines body for PostAppLogBatchDelete for application/json ContentType.
type PostAppLogBatchDeleteJSONRequestBody PostAppLogBatchDeleteJSONBody
