// Code generated by go generate ./plugins/rbac/ent; DO NOT EDIT.

package permission

import (
	internalpermission "graft/server/internal/ent/permission"
	internalpredicate "graft/server/internal/ent/predicate"
)

const (
	FieldCode = internalpermission.FieldCode
	FieldID   = internalpermission.FieldID
)

func CodeEQ(code string) internalpredicate.Permission {
	return internalpermission.CodeEQ(code)
}

func IDIn(ids ...int) internalpredicate.Permission {
	return internalpermission.IDIn(ids...)
}

func HasRolePermissionsWith(preds ...internalpredicate.RolePermission) internalpredicate.Permission {
	return internalpermission.HasRolePermissionsWith(preds...)
}
